// bindgen failed (exit 1).
// command: bindgen /Users/richbarn/Projects/picoquic/loglib/auto_memlog.h --allowlist-file '.*loglib/auto_memlog\.h$' --no-layout-tests -o /Users/richbarn/Projects/picoquic/xlate/bindgen_baseline/loglib/auto_memlog.rs -- -include /Users/richbarn/Projects/picoquic/loglib/csv.h -include /Users/richbarn/Projects/picoquic/picohttp/democlient.h -include /Users/richbarn/Projects/picoquic/picohttp/h3zero.h -include /Users/richbarn/Projects/picoquic/picohttp/h3zero_uri.h -include /Users/richbarn/Projects/picoquic/picohttp/h3zero_url_template.h -include /Users/richbarn/Projects/picoquic/picohttp/picoquic_ns.h -include /Users/richbarn/Projects/picoquic/picoquic/cc_common.h -include /Users/richbarn/Projects/picoquic/picoquic/performance_log.h -include /Users/richbarn/Projects/picoquic/picoquic/picohash.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_config.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_lb.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_qlog.h -include /Users/richbarn/Projects/picoquic/loglib/autoqlog.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_unified_log.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_logger.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_utils.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquictest_dualq.h -include /Users/richbarn/Projects/picoquic/picoquic/picosocks.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_packet_loop.h -include /Users/richbarn/Projects/picoquic/picoquic/picosplay.h -include /Users/richbarn/Projects/picoquic/picohttp/h3zero_common.h -include /Users/richbarn/Projects/picoquic/picohttp/demoserver.h -include /Users/richbarn/Projects/picoquic/picohttp/pico_webtransport.h -include /Users/richbarn/Projects/picoquic/picohttp/picomask.h -include /Users/richbarn/Projects/picoquic/picohttp/quicperf.h -include /Users/richbarn/Projects/picoquic/picohttp/wt_baton.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_internal.h -include /Users/richbarn/Projects/picoquic/loglib/cidset.h -include /Users/richbarn/Projects/picoquic/loglib/logconvert.h -include /Users/richbarn/Projects/picoquic/picoquic/bytestream.h -include /Users/richbarn/Projects/picoquic/loglib/logreader.h -include /Users/richbarn/Projects/picoquic/loglib/qlog.h -include /Users/richbarn/Projects/picoquic/loglib/svg.h -include /Users/richbarn/Projects/picoquic/picoquic/cidset.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_binlog.h -include /Users/richbarn/Projects/picoquic/picoquic/siphash.h -include /Users/richbarn/Projects/picoquic/picoquic/tls_api.h -include /Users/richbarn/Projects/picoquic/picoquictest/picoquictest.h -include /Users/richbarn/Projects/picoquic/picoquictest/picoquictest_internal.h -include /Users/richbarn/Projects/picoquic/picoquictest/picoquictest_rctl.h -include /Users/richbarn/Projects/picoquic/picoquictest/picoquictest_red.h -DPTLS_WITHOUT_FUSION -I/Users/richbarn/Projects/picoquic/build/_deps/picotls-src/include -I/Users/richbarn/Projects/picoquic/picoquic -I/Users/richbarn/Projects/picoquic/loglib -I/Users/richbarn/Projects/picoquic/c4/src -I/Users/richbarn/Projects/picoquic/picoquic_mbedtls -std=gnu11 -O3 -Wall -fno-exceptions -fno-signed-zeros -fno-trapping-math -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
// stderr:
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:57:5: error: unknown type name 'h3zero_data_stream_state_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:73:5: error: unknown type name 'picoquic_tp_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:83:5: error: unknown type name 'picoquic_alpn_enum'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:93:33: error: unknown type name 'picoquic_cnx_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:97:1: error: unknown type name 'picoquic_alpn_enum'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:98:1: error: unknown type name 'picoquic_alpn_enum'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:106:60: error: unknown type name 'picoquic_quic_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:113:40: error: unknown type name 'picoquic_cnx_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:115:35: error: unknown type name 'picoquic_cnx_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:117:5: error: unknown type name 'picoquic_call_back_event_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:35:40: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:36:51: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:37:46: error: unknown type name 'ptls_hpke_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:38:37: error: unknown type name 'ptls_hpke_kem_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:40:52: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:42:77: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:44:57: error: unknown type name 'ptls_sign_certificate_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:49:57: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:52:59: error: unknown type name 'ptls_context_t'
//   fatal error: too many errors emitted, stopping now [-ferror-limit=]
//   Unable to generate bindings: clang diagnosed error: /Users/richbarn/Projects/picoquic/picohttp/democlient.h:57:5: error: unknown type name 'h3zero_data_stream_state_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:73:5: error: unknown type name 'picoquic_tp_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:83:5: error: unknown type name 'picoquic_alpn_enum'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:93:33: error: unknown type name 'picoquic_cnx_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:97:1: error: unknown type name 'picoquic_alpn_enum'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:98:1: error: unknown type name 'picoquic_alpn_enum'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:106:60: error: unknown type name 'picoquic_quic_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:113:40: error: unknown type name 'picoquic_cnx_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:115:35: error: unknown type name 'picoquic_cnx_t'
//   /Users/richbarn/Projects/picoquic/picohttp/democlient.h:117:5: error: unknown type name 'picoquic_call_back_event_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:35:40: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:36:51: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:37:46: error: unknown type name 'ptls_hpke_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:38:37: error: unknown type name 'ptls_hpke_kem_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:40:52: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:42:77: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:44:57: error: unknown type name 'ptls_sign_certificate_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:49:57: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:52:59: error: unknown type name 'ptls_context_t'
//   fatal error: too many errors emitted, stopping now [-ferror-limit=]
//   
