//! Test cases for `picoquictest/ack_frequency*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `ackfrq_basic_test` in `picoquictest/ack_frequency_test.c`.
#[test]
fn ackfrq_basic() {
    todo!("ackfrq_basic_test")
}

/// C: `ackfrq_short_test` in `picoquictest/ack_frequency_test.c`.
#[test]
fn ackfrq_short() {
    todo!("ackfrq_short_test")
}
