//! Test cases for `picoquictest/ack_of_ack*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `ack_of_ack_test` in `picoquictest/ack_of_ack_test.c`.
#[test]
fn ack_of_ack() {
    todo!("ack_of_ack_test")
}
