//! Test cases for `picoquictest/app_limited*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `app_limited_bbr_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_bbr() {
    todo!("app_limited_bbr_test")
}

/// C: `app_limited_cubic_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_cubic() {
    todo!("app_limited_cubic_test")
}

/// C: `app_limited_reno_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_reno() {
    todo!("app_limited_reno_test")
}

/// C: `app_limited_rpr_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_rpr() {
    todo!("app_limited_rpr_test")
}
