//! Test cases for `picoquictest/cert_verify*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `cert_verify_bad_cert_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_bad_cert() {
    todo!("cert_verify_bad_cert_test")
}

/// C: `cert_verify_bad_sni_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_bad_sni() {
    todo!("cert_verify_bad_sni_test")
}

/// C: `cert_verify_null_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_null() {
    todo!("cert_verify_null_test")
}

/// C: `cert_verify_null_sni_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_null_sni() {
    todo!("cert_verify_null_sni_test")
}

/// C: `cert_verify_rsa_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_rsa() {
    todo!("cert_verify_rsa_test")
}
