//! Test cases for `picoquictest/cleartext_aead*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `cleartext_aead_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn clear_text_aead() {
    todo!("cleartext_aead_test")
}

/// C: `cleartext_pn_enc_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn cleartext_pn_enc() {
    todo!("cleartext_pn_enc_test")
}

/// C: `draft17_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn draft17_vector() {
    todo!("draft17_vector_test")
}

/// C: `key_rotation_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn key_rotation_vector() {
    todo!("key_rotation_vector_test")
}

/// C: `pn_ctr_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn pn_ctr() {
    todo!("pn_ctr_test")
}

/// C: `cleartext_pn_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn pn_vector() {
    todo!("cleartext_pn_vector_test")
}

/// C: `retry_protection_v2_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn retry_protection_v2() {
    todo!("retry_protection_v2_test")
}

/// C: `retry_protection_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn retry_protection_vector() {
    todo!("retry_protection_vector_test")
}
