//! Test cases for `picoquictest/cnx_creation*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `create_cnx_test` in `picoquictest/cnx_creation_test.c`.
#[test]
fn create_cnx() {
    todo!("create_cnx_test")
}

/// C: `create_quic_test` in `picoquictest/cnx_creation_test.c`.
#[test]
fn create_quic() {
    todo!("create_quic_test")
}
