//! Test cases for `picoquictest/congestion*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `app_limit_cc_test` in `picoquictest/congestion_test.c`.
#[test]
fn app_limit_cc() {
    todo!("app_limit_cc_test")
}

/// C: `bbr_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr() {
    todo!("bbr_test")
}

/// C: `bbr1_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr1() {
    todo!("bbr1_test")
}

/// C: `bbr1_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr1_long() {
    todo!("bbr1_long_test")
}

/// C: `bbr_asym100_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_asym100() {
    todo!("bbr_asym100_test")
}

/// C: `bbr_asym100_nodelay_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_asym100_nodelay() {
    todo!("bbr_asym100_nodelay_test")
}

/// C: `bbr_asym400_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_asym400() {
    todo!("bbr_asym400_test")
}

/// C: `gbps_performance_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_gbps() {
    todo!("gbps_performance_test")
}

/// C: `bbr_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_jitter() {
    todo!("bbr_jitter_test")
}

/// C: `bbr_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_long() {
    todo!("bbr_long_test")
}

/// C: `bbr_one_second_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_one_second() {
    todo!("bbr_one_second_test")
}

/// C: `bbr_performance_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_performance() {
    todo!("bbr_performance_test")
}

/// C: `bbr_slow_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_slow_long() {
    todo!("bbr_slow_long_test")
}

/// C: `bdp_basic_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_basic() {
    todo!("bdp_basic_test")
}

/// C: `bdp_bbr1_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_bbr1() {
    todo!("bdp_bbr1_test")
}

/// C: `bdp_cubic_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_cubic() {
    todo!("bdp_cubic_test")
}

/// C: `bdp_delay_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_delay() {
    todo!("bdp_delay_test")
}

/// C: `bdp_ip_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_ip() {
    todo!("bdp_ip_test")
}

/// C: `bdp_reno_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_reno() {
    todo!("bdp_reno_test")
}

/// C: `bdp_rtt_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_rtt() {
    todo!("bdp_rtt_test")
}

/// C: `bdp_short_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_short() {
    todo!("bdp_short_test")
}

/// C: `bdp_short_hi_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_short_hi() {
    todo!("bdp_short_hi_test")
}

/// C: `bdp_short_lo_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_short_lo() {
    todo!("bdp_short_lo_test")
}

/// C: `blackhole_test` in `picoquictest/congestion_test.c`.
#[test]
fn blackhole() {
    todo!("blackhole_test")
}

/// C: `c4_test` in `picoquictest/congestion_test.c`.
#[test]
fn c4() {
    todo!("c4_test")
}

/// C: `c4_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn c4_jitter() {
    todo!("c4_jitter_test")
}

/// C: `c4_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn c4_long() {
    todo!("c4_long_test")
}

/// C: `cubic_test` in `picoquictest/congestion_test.c`.
#[test]
fn cubic() {
    todo!("cubic_test")
}

/// C: `cubic_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn cubic_jitter() {
    todo!("cubic_jitter_test")
}

/// C: `cwin_max_test` in `picoquictest/congestion_test.c`.
#[test]
fn cwin_max() {
    todo!("cwin_max_test")
}

/// C: `fastcc_test` in `picoquictest/congestion_test.c`.
#[test]
fn fastcc() {
    todo!("fastcc_test")
}

/// C: `fastcc_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn fastcc_jitter() {
    todo!("fastcc_jitter_test")
}
