//! Test cases for `picoquictest/cpu_limited*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `limited_batch_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_batch() {
    todo!("limited_batch_test")
}

/// C: `limited_bbr_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_bbr() {
    todo!("limited_bbr_test")
}

/// C: `limited_cubic_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_cubic() {
    todo!("limited_cubic_test")
}

/// C: `limited_reno_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_reno() {
    todo!("limited_reno_test")
}

/// C: `limited_safe_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_safe() {
    todo!("limited_safe_test")
}
