//! Test cases for `picoquictest/datagram*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `datagram_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram() {
    todo!("datagram_test")
}

/// C: `datagram_loss_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_loss() {
    todo!("datagram_loss_test")
}

/// C: `datagram_rt_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_rt() {
    todo!("datagram_rt_test")
}

/// C: `datagram_rt_skip_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_rt_skip() {
    todo!("datagram_rt_skip_test")
}

/// C: `datagram_rtnew_skip_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_rtnew_skip() {
    todo!("datagram_rtnew_skip_test")
}

/// C: `datagram_size_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_size() {
    todo!("datagram_size_test")
}

/// C: `datagram_small_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_small() {
    todo!("datagram_small_test")
}

/// C: `datagram_small_new_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_small_new() {
    todo!("datagram_small_new_test")
}

/// C: `datagram_small_packet_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_small_packet() {
    todo!("datagram_small_packet_test")
}

/// C: `datagram_too_long_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_too_long_test() {
    todo!("datagram_too_long_test")
}

/// C: `datagram_wifi_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_wifi() {
    todo!("datagram_wifi_test")
}
