//! Test cases for `picoquictest/delay_tolerant*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `dtn_basic_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_basic() {
    todo!("dtn_basic_test")
}

/// C: `dtn_data_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_data() {
    todo!("dtn_data_test")
}

/// C: `dtn_silence_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_silence() {
    todo!("dtn_silence_test")
}

/// C: `dtn_twenty_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_twenty() {
    todo!("dtn_twenty_test")
}
