//! Test cases for `picoquictest/edge_cases*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `crypto_hs_offset_test` in `picoquictest/edge_cases.c`.
#[test]
fn crypto_hs_offset() {
    todo!("crypto_hs_offset_test")
}

/// C: `ec00_zero_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec00_zero() {
    todo!("ec00_zero_test")
}

/// C: `ec2f_second_flight_nack_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec2f_second_flight() {
    todo!("ec2f_second_flight_nack_test")
}

/// C: `ec5c_silly_cid_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec5c_silly_cid() {
    todo!("ec5c_silly_cid_test")
}

/// C: `ec9a_preemptive_amok_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec9a_preemptive_amok() {
    todo!("ec9a_preemptive_amok_test")
}

/// C: `eca1_amplification_loss_test` in `picoquictest/edge_cases.c`.
#[test]
fn eca1_amplification_loss() {
    todo!("eca1_amplification_loss_test")
}

/// C: `eccf_corrupted_file_fuzz_test` in `picoquictest/edge_cases.c`.
#[test]
fn eccf_corrupted_fuzz() {
    todo!("eccf_corrupted_file_fuzz_test")
}

/// C: `ecf1_final_loss_test` in `picoquictest/edge_cases.c`.
#[test]
fn ecf1_final_loss() {
    todo!("ecf1_final_loss_test")
}

/// C: `error_name_test` in `picoquictest/edge_cases.c`.
///
/// Table-driven check that every named [`crate::errors::InternalError`]
/// and [`crate::errors::TransportError`] code resolves to its
/// short textual name, plus the four "default-branch" buckets
/// (`crypto error alert`, `unknown picoquic error`, `unknown`).
#[test]
fn error_name() {
    use crate::errors::InternalError;

    let cases: &[(u64, &str)] = &[
        // Protocol (transport / TLS) errors.
        (0x1, "internal"),
        (0x2, "server busy"),
        (0x3, "flow control"),
        (0x4, "stream limit"),
        (0x5, "stream state"),
        (0x6, "final offset"),
        (0x7, "frame format"),
        (0x8, "parameter"),
        (0x9, "connection_id limit"),
        (0xA, "protocol violation"),
        (0xB, "invalid token"),
        (0xC, "application"),
        (0xD, "crypto buffer exceeded"),
        (0xE, "key update"),
        (0xF, "aead limit"),
        (0x178, "wrong alpn"),
        (0x201, "tls handshake failed"),
        (0x11, "version negotiation"),
        (0x3e, "application abandon"),
        (0x3e75, "resource limit reached"),
        (0x3e76, "unstable interface"),
        (0x3e77, "no CID available"),
        // Picoquic-internal codes (0x400+ range).
        (0x401, "duplicate"),
        (0x403, "payload_decrypt_error"),
        (0x404, "unexpected packet"),
        (0x405, "memory"),
        (0x407, "connection ID check"),
        (0x408, ""),
        (0x409, "version negotation spoofed"),
        (0x40A, "malformed transport extension"),
        (0x40B, "extension buffer too small"),
        (0x40C, "illegal transport extension"),
        (0x40D, "cannot reset the crypto stream"),
        (0x40E, "invalid stream id"),
        (0x40F, "stream already closed"),
        (0x410, "frame buffer too small"),
        (0x411, "invalid frame"),
        (0x412, "cannot control the crypto stream"),
        (0x413, "retry"),
        (0x414, "disconnected"),
        (0x415, "error detected"),
        (0x417, "invalid ticket"),
        (0x418, "invalid file"),
        (0x419, "send buffer too small"),
        (0x41A, "unexpected state"),
        (0x41B, "unexpected error"),
        (0x41C, "server configuration without cert"),
        (0x41D, "no such file"),
        (0x41E, "stateless reset"),
        (0x41F, "connection deleted"),
        (0x420, "connection ID segment error"),
        (0x421, "connection ID not available"),
        (0x422, "migration disabled"),
        (0x423, "cannot compute key"),
        (0x424, "cannot set active stream"),
        (0x425, "cannot change active context"),
        (0x426, "invalid token"),
        (0x427, "initial CID too short"),
        (0x428, "key rotation not ready"),
        (0x429, "aead not ready"),
        (0x42A, "no ALPN provided"),
        (0x42B, "no callback provided"),
        (0x42C, "stream receive complete"),
        (0x42D, "packet header parsing"),
        (0x42E, "QUIC bit missing"),
        (0x42F, "terminate packet loop (not an error)"),
        (0x430, "simulate NAT (not an error)"),
        (0x431, "simulate migration (not an error)"),
        (0x432, "version not supported"),
        (0x433, "idle timeout"),
        (0x434, "repeat timeout"),
        (0x435, "handshake timeout"),
        (0x436, "socket"),
        (0x437, "version negotiation"),
        (0x438, "packet too long"),
        (0x439, "wrong version"),
        (0x43A, "port blocked"),
        (0x43B, "datagram too long"),
        (0x43C, "invalid path ID"),
        (0x43D, "retry needed"),
        (0x43E, "server busy"),
        (0x43F, "duplicate path"),
        (0x440, "blocked by lack of path ID"),
        (0x441, "blocked by lack of CID"),
        (0x442, "path address family"),
        (0x443, "path not ready"),
        (0x444, "path limit exceeded"),
        (0x445, "redirected to proxy (not an error)"),
        (0x446, "padding_packet"),
        // CRYPTO_ERROR alert range (default branch).
        (0x101, "crypto error alert"),
        (0x150, "crypto error alert"),
        (0x1FF, "crypto error alert"),
        // Unknown picoquic error range (default branch).
        (0x450, "unknown picoquic error"),
        (0x4FF, "unknown picoquic error"),
        // Truly unknown.
        (0x0, "unknown"),
        (0x200, "unknown"),
        (0x500, "unknown"),
        (0xFFFF_FFFF_FFFF_FFFF, "unknown"),
    ];

    for &(code, expected) in cases {
        let got = InternalError::name(code).unwrap_or("<none>");
        assert_eq!(
            got, expected,
            "error_code=0x{code:x} got={got:?} expected={expected:?}",
        );
    }
}

/// C: `idle_server_test` in `picoquictest/edge_cases.c`.
#[test]
fn idle_server() {
    todo!("idle_server_test")
}

/// C: `idle_timeout_test` in `picoquictest/edge_cases.c`.
#[test]
fn idle_timeout() {
    todo!("idle_timeout_test")
}

/// C: `initial_pto_test` in `picoquictest/edge_cases.c`.
#[test]
fn initial_pto() {
    todo!("initial_pto_test")
}

/// C: `initial_pto_srv_test` in `picoquictest/edge_cases.c`.
#[test]
fn initial_pto_srv() {
    todo!("initial_pto_srv_test")
}

/// C: `reset_ack_max_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_ack_max() {
    todo!("reset_ack_max_test")
}

/// C: `reset_ack_reset_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_ack_reset() {
    todo!("reset_ack_reset_test")
}

/// C: `reset_extra_max_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_extra_max() {
    todo!("reset_extra_max_test")
}

/// C: `reset_extra_reset_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_extra_reset() {
    todo!("reset_extra_reset_test")
}

/// C: `reset_extra_stop_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_extra_stop() {
    todo!("reset_extra_stop_test")
}

/// C: `reset_loop_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_loop_test() {
    todo!("reset_loop_test")
}

/// C: `reset_need_max_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_need_max() {
    todo!("reset_need_max_test")
}

/// C: `reset_need_reset_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_need_reset() {
    todo!("reset_need_reset_test")
}

/// C: `reset_need_stop_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_need_stop() {
    todo!("reset_need_stop_test")
}

/// C: `reset_stream_at_basic_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_stream_at_basic() {
    todo!("reset_stream_at_basic_test")
}

/// C: `reset_stream_at_limit_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_stream_at_limit_test() {
    todo!("reset_stream_at_limit_test")
}

/// C: `reset_stream_at_loss_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_stream_at_loss() {
    todo!("reset_stream_at_loss_test")
}
