//! Test cases for `picoquictest/flow_control*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `flow_control_test` in `picoquictest/flow_control_test.c`.
#[test]
fn flow_control() {
    todo!("flow_control_test")
}
