//! Test cases for `picoquictest/high_latency*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `high_latency_basic_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_basic() {
    todo!("high_latency_basic_test")
}

/// C: `high_latency_bbr_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_bbr() {
    todo!("high_latency_bbr_test")
}

/// C: `high_latency_cubic_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_cubic() {
    todo!("high_latency_cubic_test")
}

/// C: `high_latency_probeRTT_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_probertt() {
    todo!("high_latency_probeRTT_test")
}
