//! Test cases for `picoquictest/l4s*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `l4s_bbr_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_bbr() {
    todo!("l4s_bbr_test")
}

/// C: `l4s_bbr_updown_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_bbr_updown() {
    todo!("l4s_bbr_updown_test")
}

/// C: `l4s_c4_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_c4() {
    todo!("l4s_c4_test")
}

/// C: `l4s_prague_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_prague() {
    todo!("l4s_prague_test")
}

/// C: `l4s_prague_updown_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_prague_updown() {
    todo!("l4s_prague_updown_test")
}

/// C: `l4s_reno_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_reno() {
    todo!("l4s_reno_test")
}
