//! Test cases for `picoquictest/mbedtls*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `mbedtls_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls() {
    todo!("mbedtls_test")
}

/// C: `mbedtls_configure_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_configure() {
    todo!("mbedtls_configure_test")
}

/// C: `mbedtls_crypto_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_crypto() {
    todo!("mbedtls_crypto_test")
}

/// C: `mbedtls_load_key_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_load_key() {
    todo!("mbedtls_load_key_test")
}

/// C: `mbedtls_load_key_fail_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_load_key_fail() {
    todo!("mbedtls_load_key_fail_test")
}

/// C: `mbedtls_retrieve_pubkey_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_retrieve_pubkey() {
    todo!("mbedtls_retrieve_pubkey_test")
}

/// C: `mbedtls_sign_verify_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_sign_verify() {
    todo!("mbedtls_sign_verify_test")
}
