//! Test cases for `picoquictest/mediatest*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `mediatest_no_coal_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_no_coal() {
    todo!("mediatest_no_coal_test")
}

/// C: `mediatest_suspension_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_suspension() {
    todo!("mediatest_suspension_test")
}

/// C: `mediatest_suspension2_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_suspension2() {
    todo!("mediatest_suspension2_test")
}

/// C: `mediatest_video_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video() {
    todo!("mediatest_video_test")
}

/// C: `mediatest_video2_back_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video2_back() {
    todo!("mediatest_video2_back_test")
}

/// C: `mediatest_video2_down_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video2_down() {
    todo!("mediatest_video2_down_test")
}

/// C: `mediatest_video2_probe_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video2_probe() {
    todo!("mediatest_video2_probe_test")
}

/// C: `mediatest_video_audio_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video_audio() {
    todo!("mediatest_video_audio_test")
}

/// C: `mediatest_video_data_audio_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video_data_audio() {
    todo!("mediatest_video_data_audio_test")
}

/// C: `mediatest_wifi_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_wifi() {
    todo!("mediatest_wifi_test")
}

/// C: `mediatest_worst_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_worst() {
    todo!("mediatest_worst_test")
}
