//! Test cases for `picoquictest/minicrypto*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `minicrypto_test` in `picoquictest/minicrypto_test.c`.
#[test]
fn minicrypto() {
    todo!("minicrypto_test")
}

/// C: `minicrypto_is_last_test` in `picoquictest/minicrypto_test.c`.
#[test]
fn minicrypto_is_last() {
    todo!("minicrypto_is_last_test")
}
