//! Test cases for `picoquictest/multipath*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `migration_controlled_test` in `picoquictest/multipath_test.c`.
#[test]
fn migration_controlled() {
    todo!("migration_controlled_test")
}

/// C: `migration_mtu_drop_test` in `picoquictest/multipath_test.c`.
#[test]
fn migration_mtu_drop() {
    todo!("migration_mtu_drop_test")
}

/// C: `monopath_0rtt_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt() {
    todo!("monopath_0rtt_test")
}

/// C: `monopath_0rtt_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt_2() {
    todo!("monopath_0rtt_test")
}

/// C: `monopath_0rtt_loss_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt_loss() {
    todo!("monopath_0rtt_loss_test")
}

/// C: `monopath_0rtt_loss_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt_loss_2() {
    todo!("monopath_0rtt_loss_test")
}

/// C: `monopath_basic_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_basic() {
    todo!("monopath_basic_test")
}

/// C: `monopath_hole_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_hole() {
    todo!("monopath_hole_test")
}

/// C: `monopath_keep_alive_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_keep_alive() {
    todo!("monopath_keep_alive_test")
}

/// C: `monopath_rotation_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_rotation() {
    todo!("monopath_rotation_test")
}

/// C: `multipath_ab1_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_ab1() {
    todo!("multipath_ab1_test")
}

/// C: `multipath_abandon_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_abandon() {
    todo!("multipath_abandon_test")
}

/// C: `multipath_aead_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_aead() {
    todo!("multipath_aead_test")
}

/// C: `multipath_back0_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_back0() {
    todo!("multipath_back0_test")
}

/// C: `multipath_back1_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_back1() {
    todo!("multipath_back1_test")
}

/// C: `multipath_backup_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_backup() {
    todo!("multipath_backup_test")
}

/// C: `multipath_basic_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_basic() {
    todo!("multipath_basic_test")
}

/// C: `multipath_break1_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_break1() {
    todo!("multipath_break1_test")
}

/// C: `multipath_break_both_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_break_both() {
    todo!("multipath_break_both_test")
}

/// C: `multipath_callback_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_callback() {
    todo!("multipath_callback_test")
}

/// C: `multipath_datagram_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_datagram() {
    todo!("multipath_datagram_test")
}

/// C: `multipath_dg_af_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_dg_af() {
    todo!("multipath_dg_af_test")
}

/// C: `multipath_discovery_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_discovery() {
    todo!("multipath_discovery_test")
}

/// C: `multipath_drop_first_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_drop_first() {
    todo!("multipath_drop_first_test")
}

/// C: `multipath_drop_second_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_drop_second() {
    todo!("multipath_drop_second_test")
}

/// C: `multipath_fail_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_fail() {
    todo!("multipath_fail_test")
}

/// C: `multipath_just_one_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_just_one() {
    todo!("multipath_just_one_test")
}

/// C: `multipath_keep_alive_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_keep_alive() {
    todo!("multipath_keep_alive_test")
}

/// C: `multipath_nat_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_nat() {
    todo!("multipath_nat_test")
}

/// C: `multipath_nat_challenge_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_nat_challenge() {
    todo!("multipath_nat_challenge_test")
}

/// C: `multipath_perf_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_perf() {
    todo!("multipath_perf_test")
}

/// C: `multipath_qlog_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_qlog() {
    todo!("multipath_qlog_test")
}

/// C: `multipath_quality_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_quality() {
    todo!("multipath_quality_test")
}

/// C: `multipath_renew_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_renew() {
    todo!("multipath_renew_test")
}

/// C: `multipath_rotation_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_rotation() {
    todo!("multipath_rotation_test")
}

/// C: `multipath_sat_plus_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_sat_plus() {
    todo!("multipath_sat_plus_test")
}

/// C: `multipath_socket0_error_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_socket0_error() {
    todo!("multipath_socket0_error_test")
}

/// C: `multipath_socket_error_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_socket_error() {
    todo!("multipath_socket_error_test")
}

/// C: `multipath_standup_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_standup() {
    todo!("multipath_standup_test")
}

/// C: `multipath_stream_af_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_stream_af() {
    todo!("multipath_stream_af_test")
}

/// C: `multipath_tunnel_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_tunnel() {
    todo!("multipath_tunnel_test")
}
