//! Test cases for `picoquictest/netperf*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `nat_attack_test` in `picoquictest/netperf_test.c`.
#[test]
fn nat_attack() {
    todo!("nat_attack_test")
}

/// C: `netperf_basic_test` in `picoquictest/netperf_test.c`.
#[test]
fn netperf_basic() {
    todo!("netperf_basic_test")
}

/// C: `netperf_bbr_test` in `picoquictest/netperf_test.c`.
#[test]
fn netperf_bbr() {
    todo!("netperf_bbr_test")
}
