//! Test cases for `picoquictest/p2p*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `address_discovery_test` in `picoquictest/p2p_test.c`.
#[test]
fn address_discovery() {
    todo!("address_discovery_test")
}
