//! Test cases for `picoquictest/pacing*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `pacing_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing() {
    todo!("pacing_test")
}

/// C: `pacing_bbr_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_bbr() {
    todo!("pacing_bbr_test")
}

/// C: `pacing_cubic_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_cubic() {
    todo!("pacing_cubic_test")
}

/// C: `pacing_dcubic_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_dcubic() {
    todo!("pacing_dcubic_test")
}

/// C: `pacing_fast_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_fast() {
    todo!("pacing_fast_test")
}

/// C: `pacing_newreno_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_newreno() {
    todo!("pacing_newreno_test")
}

/// C: `pacing_repeat_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_repeat() {
    todo!("pacing_repeat_test")
}
