//! Test cases for `picoquictest/parseheadertest*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `header_length_test` in `picoquictest/parseheadertest.c`.
#[test]
fn header_length() {
    todo!("header_length_test")
}

/// C: `incoming_initial_test` in `picoquictest/parseheadertest.c`.
#[test]
fn incoming_initial() {
    todo!("incoming_initial_test")
}

/// C: `packet_enc_dec_test` in `picoquictest/parseheadertest.c`.
#[test]
fn packet_enc_dec() {
    todo!("packet_enc_dec_test")
}

/// C: `parseheadertest` in `picoquictest/parseheadertest.c`.
#[test]
fn parseheader() {
    todo!("parseheadertest")
}
