//! Phase 3 test stubs for `crate::utils`.
//!
//! Auto-generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until Phase 3 body translation lands.

#![allow(non_snake_case)]

/// C: `util_connection_id_parse_test` in `picoquictest/util_test.c`.
#[test]
fn connection_id_parse() {
    todo!("util_connection_id_parse_test")
}

/// C: `util_connection_id_print_test` in `picoquictest/util_test.c`.
#[test]
fn connection_id_print() {
    todo!("util_connection_id_print_test")
}

/// C: `util_threading_test` in `picoquictest/util_test.c`.
#[test]
fn threading() {
    todo!("util_threading_test")
}

/// C: `util_debug_print_test` in `picoquictest/util_test.c`.
#[test]
fn util_debug_print() {
    todo!("util_debug_print_test")
}

/// C: `util_memcmp_test` in `picoquictest/util_test.c`.
#[test]
fn util_memcmp() {
    todo!("util_memcmp_test")
}

/// C: `util_sprintf_test` in `picoquictest/util_test.c`.
#[test]
fn util_sprintf() {
    todo!("util_sprintf_test")
}

/// C: `util_uint8_to_str_test` in `picoquictest/util_test.c`.
#[test]
fn util_uint8_to_str() {
    todo!("util_uint8_to_str_test")
}
