//! Phase 3 test stubs for `crate::qlog`.
//!
//! Auto-generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until Phase 3 body translation lands.

#![allow(non_snake_case)]

/// C: `qlog_auto_test` in `picoquictest/qlog_test.c`.
#[test]
fn qlog_auto() {
    todo!("qlog_auto_test")
}

/// C: `qlog_error_test` in `picoquictest/qlog_test.c`.
#[test]
fn qlog_error() {
    todo!("qlog_error_test")
}
