//! Phase 3 test stubs for `crate::packet_loop`.
//!
//! Auto-generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until Phase 3 body translation lands.

#![allow(non_snake_case)]

/// C: `sockloop_basic_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_basic() {
    todo!("sockloop_basic_test")
}

/// C: `sockloop_eio_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_eio() {
    todo!("sockloop_eio_test")
}

/// C: `sockloop_errsock_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_errsock() {
    todo!("sockloop_errsock_test")
}

/// C: `sockloop_ipv4_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_ipv4() {
    todo!("sockloop_ipv4_test")
}

/// C: `sockloop_migration_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_migration() {
    todo!("sockloop_migration_test")
}

/// C: `sockloop_nat_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_nat() {
    todo!("sockloop_nat_test")
}

/// C: `sockloop_thread_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_thread() {
    todo!("sockloop_thread_test")
}

/// C: `sockloop_thread_name_test` in `picoquictest/sockloop_test.c`.
#[test]
fn sockloop_thread_name() {
    todo!("sockloop_thread_name_test")
}
