//! Phase 3 test stubs for `crate::hash`.
//!
//! Auto-generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until Phase 3 body translation lands.

#![allow(non_snake_case)]

/// C: `picohash_test` in `picoquictest/hashtest.c`.
#[test]
fn picohash() {
    todo!("picohash_test")
}

/// C: `picohash_bytes_test` in `picoquictest/hashtest.c`.
#[test]
fn picohash_bytes() {
    todo!("picohash_bytes_test")
}

/// C: `picohash_embedded_test` in `picoquictest/hashtest.c`.
#[test]
fn picohash_embedded() {
    todo!("picohash_embedded_test")
}

/// C: `siphash_test` in `picoquictest/hashtest.c`.
#[test]
fn siphash() {
    todo!("siphash_test")
}
