//! Phase 3 test stubs for `crate::tests`.
//!
//! Auto-generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until Phase 3 body translation lands.

#![allow(non_snake_case)]

/// C: `tls_api_server_first_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn sh_loss() {
    todo!("tls_api_server_first_loss_test")
}

/// C: `StreamZeroFrameTest` in `picoquictest/stream0_frame_test.c`.
#[test]
fn streamzeroframe() {
    todo!("StreamZeroFrameTest")
}

/// C: `TlsStreamFrameTest` in `picoquictest/stream0_frame_test.c`.
#[test]
fn tlsstreamframe() {
    todo!("TlsStreamFrameTest")
}

/// C: `ack_disorder_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_disorder() {
    todo!("ack_disorder_test")
}

/// C: `ack_horizon_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_horizon() {
    todo!("ack_horizon_test")
}

/// C: `sendack_loop_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_loop() {
    todo!("sendack_loop_test")
}

/// C: `ack_of_ack_test` in `picoquictest/ack_of_ack_test.c`.
#[test]
fn ack_of_ack() {
    todo!("ack_of_ack_test")
}

/// C: `ackrange_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_range() {
    todo!("ackrange_test")
}

/// C: `sacktest` in `picoquictest/sacktest.c`.
#[test]
fn ack_sack() {
    todo!("sacktest")
}

/// C: `sendacktest` in `picoquictest/sacktest.c`.
#[test]
fn ack_send() {
    todo!("sendacktest")
}

/// C: `ackfrq_basic_test` in `picoquictest/ack_frequency_test.c`.
#[test]
fn ackfrq_basic() {
    todo!("ackfrq_basic_test")
}

/// C: `ackfrq_short_test` in `picoquictest/ack_frequency_test.c`.
#[test]
fn ackfrq_short() {
    todo!("ackfrq_short_test")
}

/// C: `address_discovery_test` in `picoquictest/p2p_test.c`.
#[test]
fn address_discovery() {
    todo!("address_discovery_test")
}

/// C: `af_undef_test` in `picoquictest/tls_api_test.c`.
#[test]
fn af_undef() {
    todo!("af_undef_test")
}

/// C: `app_limit_cc_test` in `picoquictest/congestion_test.c`.
#[test]
fn app_limit_cc() {
    todo!("app_limit_cc_test")
}

/// C: `app_limited_bbr_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_bbr() {
    todo!("app_limited_bbr_test")
}

/// C: `app_limited_cubic_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_cubic() {
    todo!("app_limited_cubic_test")
}

/// C: `app_limited_reno_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_reno() {
    todo!("app_limited_reno_test")
}

/// C: `app_limited_rpr_test` in `picoquictest/app_limited.c`.
#[test]
fn app_limited_rpr() {
    todo!("app_limited_rpr_test")
}

/// C: `app_message_overflow_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn app_message_overflow() {
    todo!("app_message_overflow_test")
}

/// C: `bad_certificate_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_certificate() {
    todo!("bad_certificate_test")
}

/// C: `bad_chello_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_chello() {
    todo!("bad_chello_test")
}

/// C: `bad_client_certificate_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_client_certificate() {
    todo!("bad_client_certificate_test")
}

/// C: `bad_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_cnxid() {
    todo!("bad_cnxid_test")
}

/// C: `bad_coalesce_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_coalesce() {
    todo!("bad_coalesce_test")
}

/// C: `bbr_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr() {
    todo!("bbr_test")
}

/// C: `bbr1_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr1() {
    todo!("bbr1_test")
}

/// C: `bbr1_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr1_long() {
    todo!("bbr1_long_test")
}

/// C: `bbr_asym100_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_asym100() {
    todo!("bbr_asym100_test")
}

/// C: `bbr_asym100_nodelay_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_asym100_nodelay() {
    todo!("bbr_asym100_nodelay_test")
}

/// C: `bbr_asym400_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_asym400() {
    todo!("bbr_asym400_test")
}

/// C: `gbps_performance_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_gbps() {
    todo!("gbps_performance_test")
}

/// C: `bbr_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_jitter() {
    todo!("bbr_jitter_test")
}

/// C: `bbr_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_long() {
    todo!("bbr_long_test")
}

/// C: `bbr_one_second_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_one_second() {
    todo!("bbr_one_second_test")
}

/// C: `bbr_performance_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_performance() {
    todo!("bbr_performance_test")
}

/// C: `bbr_slow_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn bbr_slow_long() {
    todo!("bbr_slow_long_test")
}

/// C: `bdp_basic_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_basic() {
    todo!("bdp_basic_test")
}

/// C: `bdp_bbr1_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_bbr1() {
    todo!("bdp_bbr1_test")
}

/// C: `bdp_cubic_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_cubic() {
    todo!("bdp_cubic_test")
}

/// C: `bdp_delay_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_delay() {
    todo!("bdp_delay_test")
}

/// C: `bdp_ip_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_ip() {
    todo!("bdp_ip_test")
}

/// C: `bdp_reno_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_reno() {
    todo!("bdp_reno_test")
}

/// C: `bdp_rtt_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_rtt() {
    todo!("bdp_rtt_test")
}

/// C: `bdp_short_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_short() {
    todo!("bdp_short_test")
}

/// C: `bdp_short_hi_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_short_hi() {
    todo!("bdp_short_hi_test")
}

/// C: `bdp_short_lo_test` in `picoquictest/congestion_test.c`.
#[test]
fn bdp_short_lo() {
    todo!("bdp_short_lo_test")
}

/// C: `binlog_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn binlog() {
    todo!("binlog_test")
}

/// C: `blackhole_test` in `picoquictest/congestion_test.c`.
#[test]
fn blackhole() {
    todo!("blackhole_test")
}

/// C: `c4_test` in `picoquictest/congestion_test.c`.
#[test]
fn c4() {
    todo!("c4_test")
}

/// C: `c4_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn c4_jitter() {
    todo!("c4_jitter_test")
}

/// C: `c4_long_test` in `picoquictest/congestion_test.c`.
#[test]
fn c4_long() {
    todo!("c4_long_test")
}

/// C: `cert_verify_bad_cert_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_bad_cert() {
    todo!("cert_verify_bad_cert_test")
}

/// C: `cert_verify_bad_sni_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_bad_sni() {
    todo!("cert_verify_bad_sni_test")
}

/// C: `cert_verify_null_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_null() {
    todo!("cert_verify_null_test")
}

/// C: `cert_verify_null_sni_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_null_sni() {
    todo!("cert_verify_null_sni_test")
}

/// C: `cert_verify_rsa_test` in `picoquictest/cert_verify_test.c`.
#[test]
fn cert_verify_rsa() {
    todo!("cert_verify_rsa_test")
}

/// C: `chacha20_test` in `picoquictest/tls_api_test.c`.
#[test]
fn chacha20() {
    todo!("chacha20_test")
}

/// C: `cid_for_lb_test` in `picoquictest/picoquic_lb_test.c`.
#[test]
fn cid_for_lb() {
    todo!("cid_for_lb_test")
}

/// C: `cid_for_lb_cli_test` in `picoquictest/picoquic_lb_test.c`.
#[test]
fn cid_for_lb_cli() {
    todo!("cid_for_lb_cli_test")
}

/// C: `cid_length_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cid_length() {
    todo!("cid_length_test")
}

/// C: `cid_quiescence_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cid_quiescence() {
    todo!("cid_quiescence_test")
}

/// C: `cleartext_aead_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn clear_text_aead() {
    todo!("cleartext_aead_test")
}

/// C: `cleartext_pn_enc_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn cleartext_pn_enc() {
    todo!("cleartext_pn_enc_test")
}

/// C: `request_client_authentication_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_auth() {
    todo!("request_client_authentication_test")
}

/// C: `request_client_authentication_25519_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_auth_25519() {
    todo!("request_client_authentication_25519_test")
}

/// C: `set_verify_certificate_callback_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_cert_callback() {
    todo!("set_verify_certificate_callback_test")
}

/// C: `client_error_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_error() {
    todo!("client_error_test")
}

/// C: `tls_api_client_losses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_losses() {
    todo!("tls_api_client_losses_test")
}

/// C: `client_only_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_only() {
    todo!("client_only_test")
}

/// C: `cnx_ddos_unit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnx_ddos() {
    todo!("cnx_ddos_unit_test")
}

/// C: `cnx_limit_test` in `picoquictest/cnxstress.c`.
#[test]
fn cnx_limit() {
    todo!("cnx_limit_test")
}

/// C: `cnx_stress_unit_test` in `picoquictest/cnxstress.c`.
#[test]
fn cnx_stress() {
    todo!("cnx_stress_unit_test")
}

/// C: `cnxid_renewal_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_renewal() {
    todo!("cnxid_renewal_test")
}

/// C: `transmit_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit() {
    todo!("transmit_cnxid_test")
}

/// C: `transmit_cnxid_disable_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_disable() {
    todo!("transmit_cnxid_disable_test")
}

/// C: `transmit_cnxid_retire_before_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_r_before() {
    todo!("transmit_cnxid_retire_before_test")
}

/// C: `transmit_cnxid_retire_disable_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_r_disable() {
    todo!("transmit_cnxid_retire_disable_test")
}

/// C: `transmit_cnxid_retire_early_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_r_early() {
    todo!("transmit_cnxid_retire_early_test")
}

/// C: `connection_drop_test` in `picoquictest/tls_api_test.c`.
#[test]
fn connection_drop() {
    todo!("connection_drop_test")
}

/// C: `cplusplustest` in `picoquictest/cplusplus.c`.
#[test]
fn cplusplus() {
    todo!("cplusplustest")
}

/// C: `create_cnx_test` in `picoquictest/cnx_creation_test.c`.
#[test]
fn create_cnx() {
    todo!("create_cnx_test")
}

/// C: `create_quic_test` in `picoquictest/cnx_creation_test.c`.
#[test]
fn create_quic() {
    todo!("create_quic_test")
}

/// C: `crypto_hs_offset_test` in `picoquictest/edge_cases.c`.
#[test]
fn crypto_hs_offset() {
    todo!("crypto_hs_offset_test")
}

/// C: `cubic_test` in `picoquictest/congestion_test.c`.
#[test]
fn cubic() {
    todo!("cubic_test")
}

/// C: `cubic_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn cubic_jitter() {
    todo!("cubic_jitter_test")
}

/// C: `cwin_max_test` in `picoquictest/congestion_test.c`.
#[test]
fn cwin_max() {
    todo!("cwin_max_test")
}

/// C: `datagram_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram() {
    todo!("datagram_test")
}

/// C: `datagram_loss_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_loss() {
    todo!("datagram_loss_test")
}

/// C: `datagram_rt_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_rt() {
    todo!("datagram_rt_test")
}

/// C: `datagram_rt_skip_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_rt_skip() {
    todo!("datagram_rt_skip_test")
}

/// C: `datagram_rtnew_skip_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_rtnew_skip() {
    todo!("datagram_rtnew_skip_test")
}

/// C: `datagram_size_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_size() {
    todo!("datagram_size_test")
}

/// C: `datagram_small_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_small() {
    todo!("datagram_small_test")
}

/// C: `datagram_small_new_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_small_new() {
    todo!("datagram_small_new_test")
}

/// C: `datagram_small_packet_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_small_packet() {
    todo!("datagram_small_packet_test")
}

/// C: `datagram_too_long_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_too_long_test() {
    todo!("datagram_too_long_test")
}

/// C: `datagram_wifi_test` in `picoquictest/datagram_tests.c`.
#[test]
fn datagram_wifi() {
    todo!("datagram_wifi_test")
}

/// C: `dataqueue_copy_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn dataqueue_copy() {
    todo!("dataqueue_copy_test")
}

/// C: `dataqueue_packet_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn dataqueue_packet() {
    todo!("dataqueue_packet_test")
}

/// C: `ddos_amplification_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ddos_amplification() {
    todo!("ddos_amplification_test")
}

/// C: `ddos_amplification_0rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ddos_amplification_0rtt() {
    todo!("ddos_amplification_0rtt_test")
}

/// C: `ddos_amplification_8k_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ddos_amplification_8k() {
    todo!("ddos_amplification_8k_test")
}

/// C: `tls_different_params_test` in `picoquictest/tls_api_test.c`.
#[test]
fn different_params() {
    todo!("tls_different_params_test")
}

/// C: `direct_receive_test` in `picoquictest/tls_api_test.c`.
#[test]
fn direct_receive() {
    todo!("direct_receive_test")
}

/// C: `discard_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn discard_stream() {
    todo!("discard_stream_test")
}

/// C: `document_addresses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn document_addresses() {
    todo!("document_addresses_test")
}

/// C: `draft17_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn draft17_vector() {
    todo!("draft17_vector_test")
}

/// C: `dtn_basic_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_basic() {
    todo!("dtn_basic_test")
}

/// C: `dtn_data_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_data() {
    todo!("dtn_data_test")
}

/// C: `dtn_silence_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_silence() {
    todo!("dtn_silence_test")
}

/// C: `dtn_twenty_test` in `picoquictest/delay_tolerant_test.c`.
#[test]
fn dtn_twenty() {
    todo!("dtn_twenty_test")
}

/// C: `ec00_zero_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec00_zero() {
    todo!("ec00_zero_test")
}

/// C: `ec2f_second_flight_nack_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec2f_second_flight() {
    todo!("ec2f_second_flight_nack_test")
}

/// C: `ec5c_silly_cid_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec5c_silly_cid() {
    todo!("ec5c_silly_cid_test")
}

/// C: `ec9a_preemptive_amok_test` in `picoquictest/edge_cases.c`.
#[test]
fn ec9a_preemptive_amok() {
    todo!("ec9a_preemptive_amok_test")
}

/// C: `eca1_amplification_loss_test` in `picoquictest/edge_cases.c`.
#[test]
fn eca1_amplification_loss() {
    todo!("eca1_amplification_loss_test")
}

/// C: `eccf_corrupted_file_fuzz_test` in `picoquictest/edge_cases.c`.
#[test]
fn eccf_corrupted_fuzz() {
    todo!("eccf_corrupted_file_fuzz_test")
}

/// C: `ecf1_final_loss_test` in `picoquictest/edge_cases.c`.
#[test]
fn ecf1_final_loss() {
    todo!("ecf1_final_loss_test")
}

/// C: `ech_config_test` in `picoquictest/ech_test.c`.
#[test]
fn ech_config() {
    todo!("ech_config_test")
}

/// C: `ech_config_p_test` in `picoquictest/ech_test.c`.
#[test]
fn ech_config_p() {
    todo!("ech_config_p_test")
}

/// C: `ech_e2e_test` in `picoquictest/ech_test.c`.
#[test]
fn ech_e2e() {
    todo!("ech_e2e_test")
}

/// C: `ech_e2e_0rtt_test` in `picoquictest/ech_test.c`.
#[test]
fn ech_e2e_0rtt() {
    todo!("ech_e2e_0rtt_test")
}

/// C: `ech_grease_test` in `picoquictest/ech_test.c`.
#[test]
fn ech_grease() {
    todo!("ech_grease_test")
}

/// C: `ech_no_ech_test` in `picoquictest/ech_test.c`.
#[test]
fn ech_no_ech() {
    todo!("ech_no_ech_test")
}

/// C: `error_name_test` in `picoquictest/edge_cases.c`.
#[test]
fn error_name() {
    todo!("error_name_test")
}

/// C: `error_reason_test` in `picoquictest/tls_api_test.c`.
#[test]
fn error_reason() {
    todo!("error_reason_test")
}

/// C: `excess_repeat_test` in `picoquictest/tls_api_test.c`.
#[test]
fn excess_repeat() {
    todo!("excess_repeat_test")
}

/// C: `false_migration_test` in `picoquictest/tls_api_test.c`.
#[test]
fn false_migration() {
    todo!("false_migration_test")
}

/// C: `fastcc_test` in `picoquictest/congestion_test.c`.
#[test]
fn fastcc() {
    todo!("fastcc_test")
}

/// C: `fastcc_jitter_test` in `picoquictest/congestion_test.c`.
#[test]
fn fastcc_jitter() {
    todo!("fastcc_jitter_test")
}

/// C: `tls_api_client_first_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn first_loss() {
    todo!("tls_api_client_first_loss_test")
}

/// C: `flow_control_test` in `picoquictest/flow_control_test.c`.
#[test]
fn flow_control() {
    todo!("flow_control_test")
}

/// C: `frames_ackack_error_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_ackack_error() {
    todo!("frames_ackack_error_test")
}

/// C: `frames_format_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_format() {
    todo!("frames_format_test")
}

/// C: `parse_frame_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_parse() {
    todo!("parse_frame_test")
}

/// C: `frames_repeat_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_repeat() {
    todo!("frames_repeat_test")
}

/// C: `skip_frame_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_skip() {
    todo!("skip_frame_test")
}

/// C: `fuzz_test` in `picoquictest/stresstest.c`.
#[test]
fn fuzz() {
    todo!("fuzz_test")
}

/// C: `fuzz_initial_test` in `picoquictest/stresstest.c`.
#[test]
fn fuzz_initial() {
    todo!("fuzz_initial_test")
}

/// C: `get_hash_test` in `picoquictest/tls_api_test.c`.
#[test]
fn get_hash() {
    todo!("get_hash_test")
}

/// C: `get_tls_errors_test` in `picoquictest/tls_api_test.c`.
#[test]
fn get_tls_errors() {
    todo!("get_tls_errors_test")
}

/// C: `getter_test` in `picoquictest/getter_test.c`.
#[test]
fn getter() {
    todo!("getter_test")
}

/// C: `grease_quic_bit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn grease_quic_bit() {
    todo!("grease_quic_bit_test")
}

/// C: `grease_quic_bit_one_way_test` in `picoquictest/tls_api_test.c`.
#[test]
fn grease_quic_bit_one_way() {
    todo!("grease_quic_bit_one_way_test")
}

/// C: `header_length_test` in `picoquictest/parseheadertest.c`.
#[test]
fn header_length() {
    todo!("header_length_test")
}

/// C: `heavy_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn heavy_loss() {
    todo!("heavy_loss_test")
}

/// C: `heavy_loss_inter_test` in `picoquictest/tls_api_test.c`.
#[test]
fn heavy_loss_inter() {
    todo!("heavy_loss_inter_test")
}

/// C: `heavy_loss_total_test` in `picoquictest/tls_api_test.c`.
#[test]
fn heavy_loss_total() {
    todo!("heavy_loss_total_test")
}

/// C: `high_latency_basic_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_basic() {
    todo!("high_latency_basic_test")
}

/// C: `high_latency_bbr_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_bbr() {
    todo!("high_latency_bbr_test")
}

/// C: `high_latency_cubic_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_cubic() {
    todo!("high_latency_cubic_test")
}

/// C: `high_latency_probeRTT_test` in `picoquictest/high_latency_test.c`.
#[test]
fn high_latency_probertt() {
    todo!("high_latency_probeRTT_test")
}

/// C: `idle_server_test` in `picoquictest/edge_cases.c`.
#[test]
fn idle_server() {
    todo!("idle_server_test")
}

/// C: `idle_timeout_test` in `picoquictest/edge_cases.c`.
#[test]
fn idle_timeout() {
    todo!("idle_timeout_test")
}

/// C: `immediate_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn immediate_ack() {
    todo!("immediate_ack_test")
}

/// C: `immediate_close_test` in `picoquictest/tls_api_test.c`.
#[test]
fn immediate_close() {
    todo!("immediate_close_test")
}

/// C: `implicit_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn implicit_ack() {
    todo!("implicit_ack_test")
}

/// C: `incoming_initial_test` in `picoquictest/parseheadertest.c`.
#[test]
fn incoming_initial() {
    todo!("incoming_initial_test")
}

/// C: `initial_close_test` in `picoquictest/tls_api_test.c`.
#[test]
fn initial_close() {
    todo!("initial_close_test")
}

/// C: `initial_ping_test` in `picoquictest/quic_tester.c`.
#[test]
fn initial_ping() {
    todo!("initial_ping_test")
}

/// C: `initial_ping_ack_test` in `picoquictest/quic_tester.c`.
#[test]
fn initial_ping_ack() {
    todo!("initial_ping_ack_test")
}

/// C: `initial_pto_test` in `picoquictest/edge_cases.c`.
#[test]
fn initial_pto() {
    todo!("initial_pto_test")
}

/// C: `initial_pto_srv_test` in `picoquictest/edge_cases.c`.
#[test]
fn initial_pto_srv() {
    todo!("initial_pto_srv_test")
}

/// C: `initial_race_test` in `picoquictest/tls_api_test.c`.
#[test]
fn initial_race() {
    todo!("initial_race_test")
}

/// C: `initial_server_close_test` in `picoquictest/tls_api_test.c`.
#[test]
fn initial_server_close() {
    todo!("initial_server_close_test")
}

/// C: `integrity_limit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn integrity_limit() {
    todo!("integrity_limit_test")
}

/// C: `intformattest` in `picoquictest/intformattest.c`.
#[test]
fn intformat() {
    todo!("intformattest")
}

/// C: `keep_alive_test` in `picoquictest/tls_api_test.c`.
#[test]
fn keep_alive() {
    todo!("keep_alive_test")
}

/// C: `key_rotation_test` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation() {
    todo!("key_rotation_test")
}

/// C: `key_rotation_auto_client` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation_client() {
    todo!("key_rotation_auto_client")
}

/// C: `key_rotation_auto_server` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation_server() {
    todo!("key_rotation_auto_server")
}

/// C: `key_rotation_stress_test` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation_stress() {
    todo!("key_rotation_stress_test")
}

/// C: `key_rotation_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn key_rotation_vector() {
    todo!("key_rotation_vector_test")
}

/// C: `keylog_test` in `picoquictest/tls_api_test.c`.
#[test]
fn keylog_test() {
    todo!("keylog_test")
}

/// C: `l4s_bbr_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_bbr() {
    todo!("l4s_bbr_test")
}

/// C: `l4s_bbr_updown_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_bbr_updown() {
    todo!("l4s_bbr_updown_test")
}

/// C: `l4s_c4_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_c4() {
    todo!("l4s_c4_test")
}

/// C: `l4s_prague_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_prague() {
    todo!("l4s_prague_test")
}

/// C: `l4s_prague_updown_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_prague_updown() {
    todo!("l4s_prague_updown_test")
}

/// C: `l4s_reno_test` in `picoquictest/l4s_test.c`.
#[test]
fn l4s_reno() {
    todo!("l4s_reno_test")
}

/// C: `large_client_hello_test` in `picoquictest/tls_api_test.c`.
#[test]
fn large_client_hello() {
    todo!("large_client_hello_test")
}

/// C: `limited_batch_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_batch() {
    todo!("limited_batch_test")
}

/// C: `limited_bbr_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_bbr() {
    todo!("limited_bbr_test")
}

/// C: `limited_cubic_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_cubic() {
    todo!("limited_cubic_test")
}

/// C: `limited_reno_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_reno() {
    todo!("limited_reno_test")
}

/// C: `limited_safe_test` in `picoquictest/cpu_limited.c`.
#[test]
fn limited_safe() {
    todo!("limited_safe_test")
}

/// C: `logger_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn logger() {
    todo!("logger_test")
}

/// C: `long_rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn long_rtt() {
    todo!("long_rtt_test")
}

/// C: `loss_bit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn loss_bit() {
    todo!("loss_bit_test")
}

/// C: `tls_api_many_losses` in `picoquictest/tls_api_test.c`.
#[test]
fn many_losses() {
    todo!("tls_api_many_losses")
}

/// C: `many_short_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn many_short_loss() {
    todo!("many_short_loss_test")
}

/// C: `mbedtls_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls() {
    todo!("mbedtls_test")
}

/// C: `mbedtls_configure_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_configure() {
    todo!("mbedtls_configure_test")
}

/// C: `mbedtls_crypto_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_crypto() {
    todo!("mbedtls_crypto_test")
}

/// C: `mbedtls_load_key_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_load_key() {
    todo!("mbedtls_load_key_test")
}

/// C: `mbedtls_load_key_fail_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_load_key_fail() {
    todo!("mbedtls_load_key_fail_test")
}

/// C: `mbedtls_retrieve_pubkey_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_retrieve_pubkey() {
    todo!("mbedtls_retrieve_pubkey_test")
}

/// C: `mbedtls_sign_verify_test` in `picoquictest/mbedtls_test.c`.
#[test]
fn mbedtls_sign_verify() {
    todo!("mbedtls_sign_verify_test")
}

/// C: `mediatest_no_coal_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_no_coal() {
    todo!("mediatest_no_coal_test")
}

/// C: `mediatest_suspension_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_suspension() {
    todo!("mediatest_suspension_test")
}

/// C: `mediatest_suspension2_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_suspension2() {
    todo!("mediatest_suspension2_test")
}

/// C: `mediatest_video_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video() {
    todo!("mediatest_video_test")
}

/// C: `mediatest_video2_back_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video2_back() {
    todo!("mediatest_video2_back_test")
}

/// C: `mediatest_video2_down_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video2_down() {
    todo!("mediatest_video2_down_test")
}

/// C: `mediatest_video2_probe_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video2_probe() {
    todo!("mediatest_video2_probe_test")
}

/// C: `mediatest_video_audio_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video_audio() {
    todo!("mediatest_video_audio_test")
}

/// C: `mediatest_video_data_audio_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_video_data_audio() {
    todo!("mediatest_video_data_audio_test")
}

/// C: `mediatest_wifi_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_wifi() {
    todo!("mediatest_wifi_test")
}

/// C: `mediatest_worst_test` in `picoquictest/mediatest.c`.
#[test]
fn mediatest_worst() {
    todo!("mediatest_worst_test")
}

/// C: `memlog_test` in `picoquictest/memlog_test.c`.
#[test]
fn memlog() {
    todo!("memlog_test")
}

/// C: `migration_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration() {
    todo!("migration_test")
}

/// C: `migration_controlled_test` in `picoquictest/multipath_test.c`.
#[test]
fn migration_controlled() {
    todo!("migration_controlled_test")
}

/// C: `migration_disabled_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_disabled() {
    todo!("migration_disabled_test")
}

/// C: `migration_fail_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_fail() {
    todo!("migration_fail_test")
}

/// C: `migration_test_long` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_long() {
    todo!("migration_test_long")
}

/// C: `migration_mtu_drop_test` in `picoquictest/multipath_test.c`.
#[test]
fn migration_mtu_drop() {
    todo!("migration_mtu_drop_test")
}

/// C: `migration_test_loss` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_with_loss() {
    todo!("migration_test_loss")
}

/// C: `migration_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_zero() {
    todo!("migration_zero_test")
}

/// C: `minicrypto_test` in `picoquictest/minicrypto_test.c`.
#[test]
fn minicrypto() {
    todo!("minicrypto_test")
}

/// C: `minicrypto_is_last_test` in `picoquictest/minicrypto_test.c`.
#[test]
fn minicrypto_is_last() {
    todo!("minicrypto_is_last_test")
}

/// C: `monopath_0rtt_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt() {
    todo!("monopath_0rtt_test")
}

/// C: `monopath_0rtt_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt_2() {
    todo!("monopath_0rtt_test")
}

/// C: `monopath_0rtt_loss_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt_loss() {
    todo!("monopath_0rtt_loss_test")
}

/// C: `monopath_0rtt_loss_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_0rtt_loss_2() {
    todo!("monopath_0rtt_loss_test")
}

/// C: `monopath_basic_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_basic() {
    todo!("monopath_basic_test")
}

/// C: `monopath_hole_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_hole() {
    todo!("monopath_hole_test")
}

/// C: `monopath_keep_alive_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_keep_alive() {
    todo!("monopath_keep_alive_test")
}

/// C: `monopath_rotation_test` in `picoquictest/multipath_test.c`.
#[test]
fn monopath_rotation() {
    todo!("monopath_rotation_test")
}

/// C: `mtu_blocked_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_blocked() {
    todo!("mtu_blocked_test")
}

/// C: `mtu_delayed_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_delayed() {
    todo!("mtu_delayed_test")
}

/// C: `mtu_discovery_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_discovery() {
    todo!("mtu_discovery_test")
}

/// C: `mtu_drop_bbr_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_bbr() {
    todo!("mtu_drop_bbr_test")
}

/// C: `mtu_drop_cubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_cubic() {
    todo!("mtu_drop_cubic_test")
}

/// C: `mtu_drop_dcubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_dcubic() {
    todo!("mtu_drop_dcubic_test")
}

/// C: `mtu_drop_fast_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_fast() {
    todo!("mtu_drop_fast_test")
}

/// C: `mtu_drop_newreno_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_newreno() {
    todo!("mtu_drop_newreno_test")
}

/// C: `mtu_max_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_max() {
    todo!("mtu_max_test")
}

/// C: `mtu_required_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_required() {
    todo!("mtu_required_test")
}

/// C: `multi_segment_test` in `picoquictest/tls_api_test.c`.
#[test]
fn multi_segment() {
    todo!("multi_segment_test")
}

/// C: `multipath_ab1_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_ab1() {
    todo!("multipath_ab1_test")
}

/// C: `multipath_abandon_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_abandon() {
    todo!("multipath_abandon_test")
}

/// C: `multipath_aead_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_aead() {
    todo!("multipath_aead_test")
}

/// C: `multipath_back0_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_back0() {
    todo!("multipath_back0_test")
}

/// C: `multipath_back1_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_back1() {
    todo!("multipath_back1_test")
}

/// C: `multipath_backup_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_backup() {
    todo!("multipath_backup_test")
}

/// C: `multipath_basic_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_basic() {
    todo!("multipath_basic_test")
}

/// C: `multipath_break1_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_break1() {
    todo!("multipath_break1_test")
}

/// C: `multipath_break_both_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_break_both() {
    todo!("multipath_break_both_test")
}

/// C: `multipath_callback_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_callback() {
    todo!("multipath_callback_test")
}

/// C: `multipath_datagram_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_datagram() {
    todo!("multipath_datagram_test")
}

/// C: `multipath_dg_af_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_dg_af() {
    todo!("multipath_dg_af_test")
}

/// C: `multipath_discovery_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_discovery() {
    todo!("multipath_discovery_test")
}

/// C: `multipath_drop_first_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_drop_first() {
    todo!("multipath_drop_first_test")
}

/// C: `multipath_drop_second_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_drop_second() {
    todo!("multipath_drop_second_test")
}

/// C: `multipath_fail_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_fail() {
    todo!("multipath_fail_test")
}

/// C: `multipath_just_one_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_just_one() {
    todo!("multipath_just_one_test")
}

/// C: `multipath_keep_alive_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_keep_alive() {
    todo!("multipath_keep_alive_test")
}

/// C: `multipath_nat_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_nat() {
    todo!("multipath_nat_test")
}

/// C: `multipath_nat_challenge_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_nat_challenge() {
    todo!("multipath_nat_challenge_test")
}

/// C: `multipath_perf_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_perf() {
    todo!("multipath_perf_test")
}

/// C: `multipath_qlog_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_qlog() {
    todo!("multipath_qlog_test")
}

/// C: `multipath_quality_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_quality() {
    todo!("multipath_quality_test")
}

/// C: `multipath_renew_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_renew() {
    todo!("multipath_renew_test")
}

/// C: `multipath_rotation_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_rotation() {
    todo!("multipath_rotation_test")
}

/// C: `multipath_sat_plus_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_sat_plus() {
    todo!("multipath_sat_plus_test")
}

/// C: `multipath_socket0_error_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_socket0_error() {
    todo!("multipath_socket0_error_test")
}

/// C: `multipath_socket_error_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_socket_error() {
    todo!("multipath_socket_error_test")
}

/// C: `multipath_standup_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_standup() {
    todo!("multipath_standup_test")
}

/// C: `multipath_stream_af_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_stream_af() {
    todo!("multipath_stream_af_test")
}

/// C: `multipath_tunnel_test` in `picoquictest/multipath_test.c`.
#[test]
fn multipath_tunnel() {
    todo!("multipath_tunnel_test")
}

/// C: `tls_api_multiple_versions_test` in `picoquictest/tls_api_test.c`.
#[test]
fn multiple_versions() {
    todo!("tls_api_multiple_versions_test")
}

/// C: `nat_attack_test` in `picoquictest/netperf_test.c`.
#[test]
fn nat_attack() {
    todo!("nat_attack_test")
}

/// C: `nat_handshake_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_handshake() {
    todo!("nat_handshake_test")
}

/// C: `nat_rebinding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding() {
    todo!("nat_rebinding_test")
}

/// C: `fast_nat_rebinding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_fast() {
    todo!("fast_nat_rebinding_test")
}

/// C: `nat_rebinding_latency_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_latency() {
    todo!("nat_rebinding_latency_test")
}

/// C: `nat_rebinding_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_loss() {
    todo!("nat_rebinding_loss_test")
}

/// C: `rebinding_stress_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_stress() {
    todo!("rebinding_stress_test")
}

/// C: `nat_rebinding_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_zero() {
    todo!("nat_rebinding_zero_test")
}

/// C: `netperf_basic_test` in `picoquictest/netperf_test.c`.
#[test]
fn netperf_basic() {
    todo!("netperf_basic_test")
}

/// C: `netperf_bbr_test` in `picoquictest/netperf_test.c`.
#[test]
fn netperf_bbr() {
    todo!("netperf_bbr_test")
}

/// C: `new_cnxid_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn new_cnxid() {
    todo!("new_cnxid_test")
}

/// C: `cnxid_stash_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn new_cnxid_stash() {
    todo!("cnxid_stash_test")
}

/// C: `new_rotated_key_test` in `picoquictest/tls_api_test.c`.
#[test]
fn new_rotated_key() {
    todo!("new_rotated_key_test")
}

/// C: `no_ack_frequency_test` in `picoquictest/tls_api_test.c`.
#[test]
fn no_ack_frequency() {
    todo!("no_ack_frequency_test")
}

/// C: `not_before_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn not_before_cnxid() {
    todo!("not_before_cnxid_test")
}

/// C: `null_sni_test` in `picoquictest/tls_api_test.c`.
#[test]
fn null_sni() {
    todo!("null_sni_test")
}

/// C: `openssl_cert_test` in `picoquictest/openssl_test.c`.
#[test]
fn openssl_cert() {
    todo!("openssl_cert_test")
}

/// C: `optimistic_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn optimistic_ack() {
    todo!("optimistic_ack_test")
}

/// C: `optimistic_hole_test` in `picoquictest/tls_api_test.c`.
#[test]
fn optimistic_hole() {
    todo!("optimistic_hole_test")
}

/// C: `pacing_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing() {
    todo!("pacing_test")
}

/// C: `pacing_bbr_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_bbr() {
    todo!("pacing_bbr_test")
}

/// C: `pacing_cubic_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_cubic() {
    todo!("pacing_cubic_test")
}

/// C: `pacing_dcubic_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_dcubic() {
    todo!("pacing_dcubic_test")
}

/// C: `pacing_fast_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_fast() {
    todo!("pacing_fast_test")
}

/// C: `pacing_newreno_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_newreno() {
    todo!("pacing_newreno_test")
}

/// C: `pacing_repeat_test` in `picoquictest/pacing_test.c`.
#[test]
fn pacing_repeat() {
    todo!("pacing_repeat_test")
}

/// C: `pacing_update_test` in `picoquictest/tls_api_test.c`.
#[test]
fn pacing_update() {
    todo!("pacing_update_test")
}

/// C: `packet_enc_dec_test` in `picoquictest/parseheadertest.c`.
#[test]
fn packet_enc_dec() {
    todo!("packet_enc_dec_test")
}

/// C: `packet_trace_test` in `picoquictest/tls_api_test.c`.
#[test]
fn packet_trace() {
    todo!("packet_trace_test")
}

/// C: `padding_null_test` in `picoquictest/tls_api_test.c`.
#[test]
fn padding_null() {
    todo!("padding_null_test")
}

/// C: `padding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn padding_test() {
    todo!("padding_test")
}

/// C: `padding_zero_min_test` in `picoquictest/tls_api_test.c`.
#[test]
fn padding_zero_min() {
    todo!("padding_zero_min_test")
}

/// C: `parseheadertest` in `picoquictest/parseheadertest.c`.
#[test]
fn parseheader() {
    todo!("parseheadertest")
}

/// C: `perflog_test` in `picoquictest/tls_api_test.c`.
#[test]
fn perflog() {
    todo!("perflog_test")
}

/// C: `picolog_basic_test` in `picoquictest/picolog_test.c`.
#[test]
fn picolog_basic() {
    todo!("picolog_basic_test")
}

/// C: `pn2pn64test` in `picoquictest/pn2pn64test.c`.
#[test]
fn pn2pn64() {
    todo!("pn2pn64test")
}

/// C: `pn_ctr_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn pn_ctr() {
    todo!("pn_ctr_test")
}

/// C: `pn_enc_1rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn pn_enc_1rtt() {
    todo!("pn_enc_1rtt_test")
}

/// C: `pn_random_test` in `picoquictest/tls_api_test.c`.
#[test]
fn pn_random() {
    todo!("pn_random_test")
}

/// C: `cleartext_pn_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn pn_vector() {
    todo!("cleartext_pn_vector_test")
}

/// C: `port_blocked_test` in `picoquictest/tls_api_test.c`.
#[test]
fn port_blocked() {
    todo!("port_blocked_test")
}

/// C: `preferred_address_test` in `picoquictest/tls_api_test.c`.
#[test]
fn preferred_address() {
    todo!("preferred_address_test")
}

/// C: `preferred_address_dis_mig_test` in `picoquictest/tls_api_test.c`.
#[test]
fn preferred_address_dis_mig() {
    todo!("preferred_address_dis_mig_test")
}

/// C: `preferred_address_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn preferred_address_zero() {
    todo!("preferred_address_zero_test")
}

/// C: `probe_api_test` in `picoquictest/tls_api_test.c`.
#[test]
fn probe_api() {
    todo!("probe_api_test")
}

/// C: `provide_stream_buffer_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn provide_stream_buffer() {
    todo!("provide_stream_buffer_test")
}

/// C: `qlog_fns_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_fns() {
    todo!("qlog_fns_test")
}

/// C: `qlog_fns_ecn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_fns_ecn() {
    todo!("qlog_fns_ecn_test")
}

/// C: `qlog_frames_test` in `picoquictest/qlog_frame_test.c`.
#[test]
fn qlog_frames() {
    todo!("qlog_frames_test")
}

/// C: `qlog_trace_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_trace() {
    todo!("qlog_trace_test")
}

/// C: `qlog_trace_ecn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_trace_ecn() {
    todo!("qlog_trace_ecn_test")
}

/// C: `qlog_trace_parallel_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_trace_parallel() {
    todo!("qlog_trace_parallel_test")
}

/// C: `quality_update_test` in `picoquictest/tls_api_test.c`.
#[test]
fn quality_update() {
    todo!("quality_update_test")
}

/// C: `tls_quant_params_test` in `picoquictest/tls_api_test.c`.
#[test]
fn quant_params() {
    todo!("tls_quant_params_test")
}

/// C: `queue_network_input_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn queue_network_input() {
    todo!("queue_network_input_test")
}

/// C: `random_gauss_test` in `picoquictest/stresstest.c`.
#[test]
fn random_gauss() {
    todo!("random_gauss_test")
}

/// C: `random_padding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn random_padding() {
    todo!("random_padding_test")
}

/// C: `random_public_tester_test` in `picoquictest/tls_api_test.c`.
#[test]
fn random_public_tester() {
    todo!("random_public_tester_test")
}

/// C: `random_tester_test` in `picoquictest/stresstest.c`.
#[test]
fn random_tester() {
    todo!("random_tester_test")
}

/// C: `ready_to_send_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_send() {
    todo!("ready_to_send_test")
}

/// C: `ready_to_skip_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_skip() {
    todo!("ready_to_skip_test")
}

/// C: `ready_to_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_zero() {
    todo!("ready_to_zero_test")
}

/// C: `ready_to_zfin_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_zfin() {
    todo!("ready_to_zfin_test")
}

/// C: `red_bbr_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_bbr() {
    todo!("red_bbr_test")
}

/// C: `red_cubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_cubic() {
    todo!("red_cubic_test")
}

/// C: `red_dcubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_dcubic() {
    todo!("red_dcubic_test")
}

/// C: `red_fast_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_fast() {
    todo!("red_fast_test")
}

/// C: `red_newreno_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_newreno() {
    todo!("red_newreno_test")
}

/// C: `request_client_authentication_test` in `picoquictest/tls_api_test.c`.
#[test]
fn request_client_authentication() {
    todo!("request_client_authentication_test")
}

/// C: `reset_ack_max_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_ack_max() {
    todo!("reset_ack_max_test")
}

/// C: `reset_ack_reset_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_ack_reset() {
    todo!("reset_ack_reset_test")
}

/// C: `reset_extra_max_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_extra_max() {
    todo!("reset_extra_max_test")
}

/// C: `reset_extra_reset_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_extra_reset() {
    todo!("reset_extra_reset_test")
}

/// C: `reset_extra_stop_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_extra_stop() {
    todo!("reset_extra_stop_test")
}

/// C: `reset_loop_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_loop_test() {
    todo!("reset_loop_test")
}

/// C: `reset_need_max_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_need_max() {
    todo!("reset_need_max_test")
}

/// C: `reset_need_reset_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_need_reset() {
    todo!("reset_need_reset_test")
}

/// C: `reset_need_stop_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_need_stop() {
    todo!("reset_need_stop_test")
}

/// C: `reset_stream_at_basic_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_stream_at_basic() {
    todo!("reset_stream_at_basic_test")
}

/// C: `reset_stream_at_limit_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_stream_at_limit_test() {
    todo!("reset_stream_at_limit_test")
}

/// C: `reset_stream_at_loss_test` in `picoquictest/edge_cases.c`.
#[test]
fn reset_stream_at_loss() {
    todo!("reset_stream_at_loss_test")
}

/// C: `retire_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retire_cnxid() {
    todo!("retire_cnxid_test")
}

/// C: `tls_api_retry_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry() {
    todo!("tls_api_retry_test")
}

/// C: `tls_api_retry_large_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry_large() {
    todo!("tls_api_retry_large_test")
}

/// C: `retry_protection_v2_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn retry_protection_v2() {
    todo!("retry_protection_v2_test")
}

/// C: `retry_protection_vector_test` in `picoquictest/cleartext_aead_test.c`.
#[test]
fn retry_protection_vector() {
    todo!("retry_protection_vector_test")
}

/// C: `tls_retry_token_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry_token() {
    todo!("tls_retry_token_test")
}

/// C: `tls_retry_token_valid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry_token_valid() {
    todo!("tls_retry_token_valid_test")
}

/// C: `satellite_basic_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_basic() {
    todo!("satellite_basic_test")
}

/// C: `satellite_bbr1_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_bbr1() {
    todo!("satellite_bbr1_test")
}

/// C: `satellite_cubic_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_cubic() {
    todo!("satellite_cubic_test")
}

/// C: `satellite_cubic_loss_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_cubic_loss() {
    todo!("satellite_cubic_loss_test")
}

/// C: `satellite_cubic_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_cubic_seeded() {
    todo!("satellite_cubic_seeded_test")
}

/// C: `satellite_dcubic_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_dcubic_seeded() {
    todo!("satellite_dcubic_seeded_test")
}

/// C: `satellite_jitter_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_jitter() {
    todo!("satellite_jitter_test")
}

/// C: `satellite_loss_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_loss() {
    todo!("satellite_loss_test")
}

/// C: `satellite_loss_fc_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_loss_fc() {
    todo!("satellite_loss_fc_test")
}

/// C: `satellite_medium_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_medium() {
    todo!("satellite_medium_test")
}

/// C: `satellite_prague_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_prague_seeded() {
    todo!("satellite_prague_seeded_test")
}

/// C: `satellite_preemptive_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_preemptive() {
    todo!("satellite_preemptive_test")
}

/// C: `satellite_preemptive_fc_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_preemptive_fc() {
    todo!("satellite_preemptive_fc_test")
}

/// C: `satellite_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_seeded() {
    todo!("satellite_seeded_test")
}

/// C: `satellite_seeded_bbr1_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_seeded_bbr1() {
    todo!("satellite_seeded_bbr1_test")
}

/// C: `satellite_small_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_small() {
    todo!("satellite_small_test")
}

/// C: `satellite_small_up_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_small_up() {
    todo!("satellite_small_up_test")
}

/// C: `tls_api_client_second_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn second_loss() {
    todo!("tls_api_client_second_loss_test")
}

/// C: `send_stream_blocked_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn send_stream_blocked() {
    todo!("send_stream_blocked_test")
}

/// C: `server_busy_test` in `picoquictest/tls_api_test.c`.
#[test]
fn server_busy() {
    todo!("server_busy_test")
}

/// C: `tls_api_server_losses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn server_losses() {
    todo!("tls_api_server_losses_test")
}

/// C: `session_resume_test` in `picoquictest/tls_api_test.c`.
#[test]
fn session_resume() {
    todo!("session_resume_test")
}

/// C: `set_certificate_and_key_test` in `picoquictest/tls_api_test.c`.
#[test]
fn set_certificate_and_key() {
    todo!("set_certificate_and_key_test")
}

/// C: `set_verify_certificate_callback_test` in `picoquictest/tls_api_test.c`.
#[test]
fn set_verify_certificate_callback_test() {
    todo!("set_verify_certificate_callback_test")
}

/// C: `short_initial_cid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn short_initial_cid() {
    todo!("short_initial_cid_test")
}

/// C: `tls_api_silence_test` in `picoquictest/tls_api_test.c`.
#[test]
fn silence_test() {
    todo!("tls_api_silence_test")
}

/// C: `sim_link_test` in `picoquictest/<harness>.c`.
#[test]
fn sim_link() {
    todo!("sim_link_test")
}

/// C: `socket_ecn_test` in `picoquictest/socket_test.c`.
#[test]
fn socket_ecn() {
    todo!("socket_ecn_test")
}

/// C: `socket_test` in `picoquictest/socket_test.c`.
#[test]
fn sockets() {
    todo!("socket_test")
}

/// C: `spinbit_test` in `picoquictest/spinbit_test.c`.
#[test]
fn spinbit() {
    todo!("spinbit_test")
}

/// C: `spinbit_bad_test` in `picoquictest/spinbit_test.c`.
#[test]
fn spinbit_bad() {
    todo!("spinbit_bad_test")
}

/// C: `spinbit_null_test` in `picoquictest/spinbit_test.c`.
#[test]
fn spinbit_null() {
    todo!("spinbit_null_test")
}

/// C: `spinbit_randclient_test` in `picoquictest/spinbit_test.c`.
#[test]
fn spinbit_randclient() {
    todo!("spinbit_randclient_test")
}

/// C: `spinbit_random_test` in `picoquictest/spinbit_test.c`.
#[test]
fn spinbit_random() {
    todo!("spinbit_random_test")
}

/// C: `spurious_retransmit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn spurious_retransmit() {
    todo!("spurious_retransmit_test")
}

/// C: `sqrt_for_test_test` in `picoquictest/intformattest.c`.
#[test]
fn sqrt_for_test() {
    todo!("sqrt_for_test_test")
}

/// C: `test_stateless_blowback` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_blowback() {
    todo!("test_stateless_blowback")
}

/// C: `stateless_reset_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset() {
    todo!("stateless_reset_test")
}

/// C: `stateless_reset_bad_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset_bad() {
    todo!("stateless_reset_bad_test")
}

/// C: `stateless_reset_client_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset_client() {
    todo!("stateless_reset_client_test")
}

/// C: `stateless_reset_handshake_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset_handshake() {
    todo!("stateless_reset_handshake_test")
}

/// C: `stop_sending_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stop_sending() {
    todo!("stop_sending_test")
}

/// C: `stop_sending_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stop_sending_loss() {
    todo!("stop_sending_loss_test")
}

/// C: `stream_ack_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn stream_ack() {
    todo!("stream_ack_test")
}

/// C: `stream_id_max_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stream_id_max() {
    todo!("stream_id_max_test")
}

/// C: `stream_output_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_output() {
    todo!("stream_output_test")
}

/// C: `stream_rank_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_rank() {
    todo!("stream_rank_test")
}

/// C: `test_copy_for_retransmit` in `picoquictest/skip_frame_test.c`.
#[test]
fn stream_retransmit_copy() {
    todo!("test_copy_for_retransmit")
}

/// C: `stream_splay_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_splay() {
    todo!("stream_splay_test")
}

/// C: `stream_state_local_reuse_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_state_local_reuse() {
    todo!("stream_state_local_reuse_test")
}

/// C: `stress_test` in `picoquictest/stresstest.c`.
#[test]
fn stress() {
    todo!("stress_test")
}

/// C: `ticket_seed_test` in `picoquictest/ticket_store_test.c`.
#[test]
fn ticket_seed() {
    todo!("ticket_seed_test")
}

/// C: `ticket_seed_from_bdp_frame_test` in `picoquictest/ticket_store_test.c`.
#[test]
fn ticket_seed_from_bdp_frame() {
    todo!("ticket_seed_from_bdp_frame_test")
}

/// C: `ticket_store_test` in `picoquictest/ticket_store_test.c`.
#[test]
fn ticket_store() {
    todo!("ticket_store_test")
}

/// C: `tls_api_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api() {
    todo!("tls_api_test")
}

/// C: `tls_api_alpn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_alpn() {
    todo!("tls_api_alpn_test")
}

/// C: `tls_api_connect_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_connect() {
    todo!("tls_api_connect_test")
}

/// C: `tls_api_inject_hs_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_inject_hs_ack() {
    todo!("tls_api_inject_hs_ack_test")
}

/// C: `tls_api_oneway_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_oneway_stream() {
    todo!("tls_api_oneway_stream_test")
}

/// C: `tls_api_q2_and_r2_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_q2_and_r2_stream() {
    todo!("tls_api_q2_and_r2_stream_test")
}

/// C: `tls_api_q_and_r_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_q_and_r_stream() {
    todo!("tls_api_q_and_r_stream_test")
}

/// C: `tls_api_sni_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_sni() {
    todo!("tls_api_sni_test")
}

/// C: `tls_api_very_long_congestion_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_congestion() {
    todo!("tls_api_very_long_congestion_test")
}

/// C: `tls_api_very_long_max_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_max() {
    todo!("tls_api_very_long_max_test")
}

/// C: `tls_api_very_long_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_stream() {
    todo!("tls_api_very_long_stream_test")
}

/// C: `tls_api_very_long_with_err_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_with_err() {
    todo!("tls_api_very_long_with_err_test")
}

/// C: `tls_api_wrong_alpn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_wrong_alpn() {
    todo!("tls_api_wrong_alpn_test")
}

/// C: `tls_exporter_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_exporter() {
    todo!("tls_exporter_test")
}

/// C: `tls_zero_share_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_zero_share() {
    todo!("tls_zero_share_test")
}

/// C: `token_reuse_api_test` in `picoquictest/ticket_store_test.c`.
#[test]
fn token_reuse_api() {
    todo!("token_reuse_api_test")
}

/// C: `token_store_test` in `picoquictest/ticket_store_test.c`.
#[test]
fn token_store() {
    todo!("token_store_test")
}

/// C: `transport_param_test` in `picoquictest/transport_param_test.c`.
#[test]
fn transport_param() {
    todo!("transport_param_test")
}

/// C: `transport_param_default_test` in `picoquictest/transport_param_test.c`.
#[test]
fn transport_param_default() {
    todo!("transport_param_default_test")
}

/// C: `transport_param_log_test` in `picoquictest/transport_param_test.c`.
#[test]
fn transport_param_log() {
    todo!("transport_param_log_test")
}

/// C: `tls_api_two_connections_test` in `picoquictest/tls_api_test.c`.
#[test]
fn two_connections() {
    todo!("tls_api_two_connections_test")
}

/// C: `unidir_test` in `picoquictest/tls_api_test.c`.
#[test]
fn unidir() {
    todo!("unidir_test")
}

/// C: `varint_test` in `picoquictest/intformattest.c`.
#[test]
fn varint() {
    todo!("varint_test")
}

/// C: `tls_api_version_invariant_test` in `picoquictest/tls_api_test.c`.
#[test]
fn version_invariant() {
    todo!("tls_api_version_invariant_test")
}

/// C: `tls_api_version_negotiation_test` in `picoquictest/tls_api_test.c`.
#[test]
fn version_negotiation() {
    todo!("tls_api_version_negotiation_test")
}

/// C: `test_version_negotiation_spoof` in `picoquictest/tls_api_test.c`.
#[test]
fn version_negotiation_spoof() {
    todo!("test_version_negotiation_spoof")
}

/// C: `virtual_time_test` in `picoquictest/tls_api_test.c`.
#[test]
fn virtual_time() {
    todo!("virtual_time_test")
}

/// C: `vn_compat_test` in `picoquictest/tls_api_test.c`.
#[test]
fn vn_compat() {
    todo!("vn_compat_test")
}

/// C: `vn_tp_test` in `picoquictest/transport_param_test.c`.
#[test]
fn vn_tp() {
    todo!("vn_tp_test")
}

/// C: `warptest_param_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_param() {
    todo!("warptest_param_test")
}

/// C: `warptest_video_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_video() {
    todo!("warptest_video_test")
}

/// C: `warptest_video_audio_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_video_audio() {
    todo!("warptest_video_audio_test")
}

/// C: `warptest_video_data_audio_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_video_data_audio() {
    todo!("warptest_video_data_audio_test")
}

/// C: `warptest_worst_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_worst() {
    todo!("warptest_worst_test")
}

/// C: `wifi_bbr_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr() {
    todo!("wifi_bbr_test")
}

/// C: `wifi_bbr1_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr1() {
    todo!("wifi_bbr1_test")
}

/// C: `wifi_bbr1_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr1_hard() {
    todo!("wifi_bbr1_hard_test")
}

/// C: `wifi_bbr1_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr1_long() {
    todo!("wifi_bbr1_long_test")
}

/// C: `wifi_bbr_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_hard() {
    todo!("wifi_bbr_hard_test")
}

/// C: `wifi_bbr_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_long() {
    todo!("wifi_bbr_long_test")
}

/// C: `wifi_bbr_many_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_many() {
    todo!("wifi_bbr_many_test")
}

/// C: `wifi_bbr_shadow_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_shadow() {
    todo!("wifi_bbr_shadow_test")
}

/// C: `wifi_cubic_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_cubic() {
    todo!("wifi_cubic_test")
}

/// C: `wifi_cubic_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_cubic_hard() {
    todo!("wifi_cubic_hard_test")
}

/// C: `wifi_cubic_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_cubic_long() {
    todo!("wifi_cubic_long_test")
}

/// C: `wifi_reno_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_reno() {
    todo!("wifi_reno_test")
}

/// C: `wifi_reno_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_reno_hard() {
    todo!("wifi_reno_hard_test")
}

/// C: `wifi_reno_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_reno_long() {
    todo!("wifi_reno_long_test")
}

/// C: `zero_rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt() {
    todo!("zero_rtt_test")
}

/// C: `zero_rtt_bad_param_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_bad_param() {
    todo!("zero_rtt_bad_param_test")
}

/// C: `zero_rtt_delay_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_delay() {
    todo!("zero_rtt_delay_test")
}

/// C: `zero_rtt_ech_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_ech() {
    todo!("zero_rtt_ech_test")
}

/// C: `zero_rtt_long_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_long() {
    todo!("zero_rtt_long_test")
}

/// C: `zero_rtt_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_loss() {
    todo!("zero_rtt_loss_test")
}

/// C: `zero_rtt_many_losses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_many_losses() {
    todo!("zero_rtt_many_losses_test")
}

/// C: `zero_rtt_no_coal_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_no_coal() {
    todo!("zero_rtt_no_coal_test")
}

/// C: `zero_rtt_retry_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_retry() {
    todo!("zero_rtt_retry_test")
}

/// C: `zero_rtt_spurious_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_spurious() {
    todo!("zero_rtt_spurious_test")
}
