//! Phase 3 test stubs for `crate::splay`.
//!
//! Auto-generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until Phase 3 body translation lands.

#![allow(non_snake_case)]

/// C: `splay_test` in `picoquictest/splay_test.c`.
#[test]
fn splay() {
    todo!("splay_test")
}
