//! Test cases for `picoquictest/quic_tester*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `initial_ping_test` in `picoquictest/quic_tester.c`.
#[test]
fn initial_ping() {
    todo!("initial_ping_test")
}

/// C: `initial_ping_ack_test` in `picoquictest/quic_tester.c`.
#[test]
fn initial_ping_ack() {
    todo!("initial_ping_ack_test")
}
