//! Test cases for `picoquictest/sacktest*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `ack_disorder_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_disorder() {
    todo!("ack_disorder_test")
}

/// C: `ack_horizon_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_horizon() {
    todo!("ack_horizon_test")
}

/// C: `sendack_loop_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_loop() {
    todo!("sendack_loop_test")
}

/// C: `ackrange_test` in `picoquictest/sacktest.c`.
#[test]
fn ack_range() {
    todo!("ackrange_test")
}

/// C: `sacktest` in `picoquictest/sacktest.c`.
#[test]
fn ack_sack() {
    todo!("sacktest")
}

/// C: `sendacktest` in `picoquictest/sacktest.c`.
#[test]
fn ack_send() {
    todo!("sendacktest")
}
