//! Test cases for `picoquictest/satellite*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `satellite_basic_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_basic() {
    todo!("satellite_basic_test")
}

/// C: `satellite_bbr1_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_bbr1() {
    todo!("satellite_bbr1_test")
}

/// C: `satellite_cubic_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_cubic() {
    todo!("satellite_cubic_test")
}

/// C: `satellite_cubic_loss_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_cubic_loss() {
    todo!("satellite_cubic_loss_test")
}

/// C: `satellite_cubic_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_cubic_seeded() {
    todo!("satellite_cubic_seeded_test")
}

/// C: `satellite_dcubic_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_dcubic_seeded() {
    todo!("satellite_dcubic_seeded_test")
}

/// C: `satellite_jitter_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_jitter() {
    todo!("satellite_jitter_test")
}

/// C: `satellite_loss_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_loss() {
    todo!("satellite_loss_test")
}

/// C: `satellite_loss_fc_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_loss_fc() {
    todo!("satellite_loss_fc_test")
}

/// C: `satellite_medium_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_medium() {
    todo!("satellite_medium_test")
}

/// C: `satellite_prague_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_prague_seeded() {
    todo!("satellite_prague_seeded_test")
}

/// C: `satellite_preemptive_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_preemptive() {
    todo!("satellite_preemptive_test")
}

/// C: `satellite_preemptive_fc_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_preemptive_fc() {
    todo!("satellite_preemptive_fc_test")
}

/// C: `satellite_seeded_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_seeded() {
    todo!("satellite_seeded_test")
}

/// C: `satellite_seeded_bbr1_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_seeded_bbr1() {
    todo!("satellite_seeded_bbr1_test")
}

/// C: `satellite_small_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_small() {
    todo!("satellite_small_test")
}

/// C: `satellite_small_up_test` in `picoquictest/satellite_test.c`.
#[test]
fn satellite_small_up() {
    todo!("satellite_small_up_test")
}
