//! Test cases for `picoquictest/skip_frame*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `app_message_overflow_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn app_message_overflow() {
    todo!("app_message_overflow_test")
}

/// C: `binlog_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn binlog() {
    todo!("binlog_test")
}

/// C: `dataqueue_copy_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn dataqueue_copy() {
    todo!("dataqueue_copy_test")
}

/// C: `dataqueue_packet_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn dataqueue_packet() {
    todo!("dataqueue_packet_test")
}

/// C: `frames_ackack_error_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_ackack_error() {
    todo!("frames_ackack_error_test")
}

/// C: `frames_format_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_format() {
    todo!("frames_format_test")
}

/// C: `parse_frame_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_parse() {
    todo!("parse_frame_test")
}

/// C: `frames_repeat_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_repeat() {
    todo!("frames_repeat_test")
}

/// C: `skip_frame_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn frames_skip() {
    todo!("skip_frame_test")
}

/// C: `logger_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn logger() {
    todo!("logger_test")
}

/// C: `new_cnxid_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn new_cnxid() {
    todo!("new_cnxid_test")
}

/// C: `cnxid_stash_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn new_cnxid_stash() {
    todo!("cnxid_stash_test")
}

/// C: `queue_network_input_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn queue_network_input() {
    todo!("queue_network_input_test")
}

/// C: `send_stream_blocked_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn send_stream_blocked() {
    todo!("send_stream_blocked_test")
}

/// C: `stream_ack_test` in `picoquictest/skip_frame_test.c`.
#[test]
fn stream_ack() {
    todo!("stream_ack_test")
}

/// C: `test_copy_for_retransmit` in `picoquictest/skip_frame_test.c`.
#[test]
fn stream_retransmit_copy() {
    todo!("test_copy_for_retransmit")
}
