//! Test cases for `picoquictest/socket*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `socket_ecn_test` in `picoquictest/socket_test.c`.
#[test]
fn socket_ecn() {
    todo!("socket_ecn_test")
}

/// C: `socket_test` in `picoquictest/socket_test.c`.
#[test]
fn sockets() {
    todo!("socket_test")
}
