//! Test cases for `picoquictest/stream0_frame*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `StreamZeroFrameTest` in `picoquictest/stream0_frame_test.c`.
#[test]
fn streamzeroframe() {
    todo!("StreamZeroFrameTest")
}

/// C: `TlsStreamFrameTest` in `picoquictest/stream0_frame_test.c`.
#[test]
fn tlsstreamframe() {
    todo!("TlsStreamFrameTest")
}

/// C: `provide_stream_buffer_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn provide_stream_buffer() {
    todo!("provide_stream_buffer_test")
}

/// C: `stream_output_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_output() {
    todo!("stream_output_test")
}

/// C: `stream_rank_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_rank() {
    todo!("stream_rank_test")
}

/// C: `stream_splay_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_splay() {
    todo!("stream_splay_test")
}

/// C: `stream_state_local_reuse_test` in `picoquictest/stream0_frame_test.c`.
#[test]
fn stream_state_local_reuse() {
    todo!("stream_state_local_reuse_test")
}
