//! Test cases for `picoquictest/tls_api*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `tls_api_server_first_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn sh_loss() {
    todo!("tls_api_server_first_loss_test")
}

/// C: `af_undef_test` in `picoquictest/tls_api_test.c`.
#[test]
fn af_undef() {
    todo!("af_undef_test")
}

/// C: `bad_certificate_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_certificate() {
    todo!("bad_certificate_test")
}

/// C: `bad_chello_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_chello() {
    todo!("bad_chello_test")
}

/// C: `bad_client_certificate_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_client_certificate() {
    todo!("bad_client_certificate_test")
}

/// C: `bad_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_cnxid() {
    todo!("bad_cnxid_test")
}

/// C: `bad_coalesce_test` in `picoquictest/tls_api_test.c`.
#[test]
fn bad_coalesce() {
    todo!("bad_coalesce_test")
}

/// C: `chacha20_test` in `picoquictest/tls_api_test.c`.
#[test]
fn chacha20() {
    todo!("chacha20_test")
}

/// C: `cid_length_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cid_length() {
    todo!("cid_length_test")
}

/// C: `cid_quiescence_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cid_quiescence() {
    todo!("cid_quiescence_test")
}

/// C: `request_client_authentication_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_auth() {
    todo!("request_client_authentication_test")
}

/// C: `request_client_authentication_25519_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_auth_25519() {
    todo!("request_client_authentication_25519_test")
}

/// C: `set_verify_certificate_callback_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_cert_callback() {
    todo!("set_verify_certificate_callback_test")
}

/// C: `client_error_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_error() {
    todo!("client_error_test")
}

/// C: `tls_api_client_losses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_losses() {
    todo!("tls_api_client_losses_test")
}

/// C: `client_only_test` in `picoquictest/tls_api_test.c`.
#[test]
fn client_only() {
    todo!("client_only_test")
}

/// C: `cnx_ddos_unit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnx_ddos() {
    todo!("cnx_ddos_unit_test")
}

/// C: `cnxid_renewal_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_renewal() {
    todo!("cnxid_renewal_test")
}

/// C: `transmit_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit() {
    todo!("transmit_cnxid_test")
}

/// C: `transmit_cnxid_disable_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_disable() {
    todo!("transmit_cnxid_disable_test")
}

/// C: `transmit_cnxid_retire_before_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_r_before() {
    todo!("transmit_cnxid_retire_before_test")
}

/// C: `transmit_cnxid_retire_disable_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_r_disable() {
    todo!("transmit_cnxid_retire_disable_test")
}

/// C: `transmit_cnxid_retire_early_test` in `picoquictest/tls_api_test.c`.
#[test]
fn cnxid_transmit_r_early() {
    todo!("transmit_cnxid_retire_early_test")
}

/// C: `connection_drop_test` in `picoquictest/tls_api_test.c`.
#[test]
fn connection_drop() {
    todo!("connection_drop_test")
}

/// C: `ddos_amplification_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ddos_amplification() {
    todo!("ddos_amplification_test")
}

/// C: `ddos_amplification_0rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ddos_amplification_0rtt() {
    todo!("ddos_amplification_0rtt_test")
}

/// C: `ddos_amplification_8k_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ddos_amplification_8k() {
    todo!("ddos_amplification_8k_test")
}

/// C: `tls_different_params_test` in `picoquictest/tls_api_test.c`.
#[test]
fn different_params() {
    todo!("tls_different_params_test")
}

/// C: `direct_receive_test` in `picoquictest/tls_api_test.c`.
#[test]
fn direct_receive() {
    todo!("direct_receive_test")
}

/// C: `discard_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn discard_stream() {
    todo!("discard_stream_test")
}

/// C: `document_addresses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn document_addresses() {
    todo!("document_addresses_test")
}

/// C: `error_reason_test` in `picoquictest/tls_api_test.c`.
#[test]
fn error_reason() {
    todo!("error_reason_test")
}

/// C: `excess_repeat_test` in `picoquictest/tls_api_test.c`.
#[test]
fn excess_repeat() {
    todo!("excess_repeat_test")
}

/// C: `false_migration_test` in `picoquictest/tls_api_test.c`.
#[test]
fn false_migration() {
    todo!("false_migration_test")
}

/// C: `tls_api_client_first_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn first_loss() {
    todo!("tls_api_client_first_loss_test")
}

/// C: `get_hash_test` in `picoquictest/tls_api_test.c`.
#[test]
fn get_hash() {
    todo!("get_hash_test")
}

/// C: `get_tls_errors_test` in `picoquictest/tls_api_test.c`.
#[test]
fn get_tls_errors() {
    todo!("get_tls_errors_test")
}

/// C: `grease_quic_bit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn grease_quic_bit() {
    todo!("grease_quic_bit_test")
}

/// C: `grease_quic_bit_one_way_test` in `picoquictest/tls_api_test.c`.
#[test]
fn grease_quic_bit_one_way() {
    todo!("grease_quic_bit_one_way_test")
}

/// C: `heavy_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn heavy_loss() {
    todo!("heavy_loss_test")
}

/// C: `heavy_loss_inter_test` in `picoquictest/tls_api_test.c`.
#[test]
fn heavy_loss_inter() {
    todo!("heavy_loss_inter_test")
}

/// C: `heavy_loss_total_test` in `picoquictest/tls_api_test.c`.
#[test]
fn heavy_loss_total() {
    todo!("heavy_loss_total_test")
}

/// C: `immediate_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn immediate_ack() {
    todo!("immediate_ack_test")
}

/// C: `immediate_close_test` in `picoquictest/tls_api_test.c`.
#[test]
fn immediate_close() {
    todo!("immediate_close_test")
}

/// C: `implicit_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn implicit_ack() {
    todo!("implicit_ack_test")
}

/// C: `initial_close_test` in `picoquictest/tls_api_test.c`.
#[test]
fn initial_close() {
    todo!("initial_close_test")
}

/// C: `initial_race_test` in `picoquictest/tls_api_test.c`.
#[test]
fn initial_race() {
    todo!("initial_race_test")
}

/// C: `initial_server_close_test` in `picoquictest/tls_api_test.c`.
#[test]
fn initial_server_close() {
    todo!("initial_server_close_test")
}

/// C: `integrity_limit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn integrity_limit() {
    todo!("integrity_limit_test")
}

/// C: `keep_alive_test` in `picoquictest/tls_api_test.c`.
#[test]
fn keep_alive() {
    todo!("keep_alive_test")
}

/// C: `key_rotation_test` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation() {
    todo!("key_rotation_test")
}

/// C: `key_rotation_auto_client` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation_client() {
    todo!("key_rotation_auto_client")
}

/// C: `key_rotation_auto_server` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation_server() {
    todo!("key_rotation_auto_server")
}

/// C: `key_rotation_stress_test` in `picoquictest/tls_api_test.c`.
#[test]
fn key_rotation_stress() {
    todo!("key_rotation_stress_test")
}

/// C: `keylog_test` in `picoquictest/tls_api_test.c`.
#[test]
fn keylog_test() {
    todo!("keylog_test")
}

/// C: `large_client_hello_test` in `picoquictest/tls_api_test.c`.
#[test]
fn large_client_hello() {
    todo!("large_client_hello_test")
}

/// C: `long_rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn long_rtt() {
    todo!("long_rtt_test")
}

/// C: `loss_bit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn loss_bit() {
    todo!("loss_bit_test")
}

/// C: `tls_api_many_losses` in `picoquictest/tls_api_test.c`.
#[test]
fn many_losses() {
    todo!("tls_api_many_losses")
}

/// C: `many_short_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn many_short_loss() {
    todo!("many_short_loss_test")
}

/// C: `migration_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration() {
    todo!("migration_test")
}

/// C: `migration_disabled_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_disabled() {
    todo!("migration_disabled_test")
}

/// C: `migration_fail_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_fail() {
    todo!("migration_fail_test")
}

/// C: `migration_test_long` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_long() {
    todo!("migration_test_long")
}

/// C: `migration_test_loss` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_with_loss() {
    todo!("migration_test_loss")
}

/// C: `migration_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn migration_zero() {
    todo!("migration_zero_test")
}

/// C: `mtu_blocked_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_blocked() {
    todo!("mtu_blocked_test")
}

/// C: `mtu_delayed_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_delayed() {
    todo!("mtu_delayed_test")
}

/// C: `mtu_discovery_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_discovery() {
    todo!("mtu_discovery_test")
}

/// C: `mtu_drop_bbr_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_bbr() {
    todo!("mtu_drop_bbr_test")
}

/// C: `mtu_drop_cubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_cubic() {
    todo!("mtu_drop_cubic_test")
}

/// C: `mtu_drop_dcubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_dcubic() {
    todo!("mtu_drop_dcubic_test")
}

/// C: `mtu_drop_fast_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_fast() {
    todo!("mtu_drop_fast_test")
}

/// C: `mtu_drop_newreno_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_drop_newreno() {
    todo!("mtu_drop_newreno_test")
}

/// C: `mtu_max_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_max() {
    todo!("mtu_max_test")
}

/// C: `mtu_required_test` in `picoquictest/tls_api_test.c`.
#[test]
fn mtu_required() {
    todo!("mtu_required_test")
}

/// C: `multi_segment_test` in `picoquictest/tls_api_test.c`.
#[test]
fn multi_segment() {
    todo!("multi_segment_test")
}

/// C: `tls_api_multiple_versions_test` in `picoquictest/tls_api_test.c`.
#[test]
fn multiple_versions() {
    todo!("tls_api_multiple_versions_test")
}

/// C: `nat_handshake_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_handshake() {
    todo!("nat_handshake_test")
}

/// C: `nat_rebinding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding() {
    todo!("nat_rebinding_test")
}

/// C: `fast_nat_rebinding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_fast() {
    todo!("fast_nat_rebinding_test")
}

/// C: `nat_rebinding_latency_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_latency() {
    todo!("nat_rebinding_latency_test")
}

/// C: `nat_rebinding_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_loss() {
    todo!("nat_rebinding_loss_test")
}

/// C: `rebinding_stress_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_stress() {
    todo!("rebinding_stress_test")
}

/// C: `nat_rebinding_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn nat_rebinding_zero() {
    todo!("nat_rebinding_zero_test")
}

/// C: `new_rotated_key_test` in `picoquictest/tls_api_test.c`.
#[test]
fn new_rotated_key() {
    todo!("new_rotated_key_test")
}

/// C: `no_ack_frequency_test` in `picoquictest/tls_api_test.c`.
#[test]
fn no_ack_frequency() {
    todo!("no_ack_frequency_test")
}

/// C: `not_before_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn not_before_cnxid() {
    todo!("not_before_cnxid_test")
}

/// C: `null_sni_test` in `picoquictest/tls_api_test.c`.
#[test]
fn null_sni() {
    todo!("null_sni_test")
}

/// C: `optimistic_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn optimistic_ack() {
    todo!("optimistic_ack_test")
}

/// C: `optimistic_hole_test` in `picoquictest/tls_api_test.c`.
#[test]
fn optimistic_hole() {
    todo!("optimistic_hole_test")
}

/// C: `pacing_update_test` in `picoquictest/tls_api_test.c`.
#[test]
fn pacing_update() {
    todo!("pacing_update_test")
}

/// C: `packet_trace_test` in `picoquictest/tls_api_test.c`.
#[test]
fn packet_trace() {
    todo!("packet_trace_test")
}

/// C: `padding_null_test` in `picoquictest/tls_api_test.c`.
#[test]
fn padding_null() {
    todo!("padding_null_test")
}

/// C: `padding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn padding_test() {
    todo!("padding_test")
}

/// C: `padding_zero_min_test` in `picoquictest/tls_api_test.c`.
#[test]
fn padding_zero_min() {
    todo!("padding_zero_min_test")
}

/// C: `perflog_test` in `picoquictest/tls_api_test.c`.
#[test]
fn perflog() {
    todo!("perflog_test")
}

/// C: `pn_enc_1rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn pn_enc_1rtt() {
    todo!("pn_enc_1rtt_test")
}

/// C: `pn_random_test` in `picoquictest/tls_api_test.c`.
#[test]
fn pn_random() {
    todo!("pn_random_test")
}

/// C: `port_blocked_test` in `picoquictest/tls_api_test.c`.
#[test]
fn port_blocked() {
    todo!("port_blocked_test")
}

/// C: `preferred_address_test` in `picoquictest/tls_api_test.c`.
#[test]
fn preferred_address() {
    todo!("preferred_address_test")
}

/// C: `preferred_address_dis_mig_test` in `picoquictest/tls_api_test.c`.
#[test]
fn preferred_address_dis_mig() {
    todo!("preferred_address_dis_mig_test")
}

/// C: `preferred_address_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn preferred_address_zero() {
    todo!("preferred_address_zero_test")
}

/// C: `probe_api_test` in `picoquictest/tls_api_test.c`.
#[test]
fn probe_api() {
    todo!("probe_api_test")
}

/// C: `qlog_fns_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_fns() {
    todo!("qlog_fns_test")
}

/// C: `qlog_fns_ecn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_fns_ecn() {
    todo!("qlog_fns_ecn_test")
}

/// C: `qlog_trace_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_trace() {
    todo!("qlog_trace_test")
}

/// C: `qlog_trace_ecn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_trace_ecn() {
    todo!("qlog_trace_ecn_test")
}

/// C: `qlog_trace_parallel_test` in `picoquictest/tls_api_test.c`.
#[test]
fn qlog_trace_parallel() {
    todo!("qlog_trace_parallel_test")
}

/// C: `quality_update_test` in `picoquictest/tls_api_test.c`.
#[test]
fn quality_update() {
    todo!("quality_update_test")
}

/// C: `tls_quant_params_test` in `picoquictest/tls_api_test.c`.
#[test]
fn quant_params() {
    todo!("tls_quant_params_test")
}

/// C: `random_padding_test` in `picoquictest/tls_api_test.c`.
#[test]
fn random_padding() {
    todo!("random_padding_test")
}

/// C: `random_public_tester_test` in `picoquictest/tls_api_test.c`.
#[test]
fn random_public_tester() {
    todo!("random_public_tester_test")
}

/// C: `ready_to_send_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_send() {
    todo!("ready_to_send_test")
}

/// C: `ready_to_skip_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_skip() {
    todo!("ready_to_skip_test")
}

/// C: `ready_to_zero_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_zero() {
    todo!("ready_to_zero_test")
}

/// C: `ready_to_zfin_test` in `picoquictest/tls_api_test.c`.
#[test]
fn ready_to_zfin() {
    todo!("ready_to_zfin_test")
}

/// C: `red_bbr_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_bbr() {
    todo!("red_bbr_test")
}

/// C: `red_cubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_cubic() {
    todo!("red_cubic_test")
}

/// C: `red_dcubic_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_dcubic() {
    todo!("red_dcubic_test")
}

/// C: `red_fast_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_fast() {
    todo!("red_fast_test")
}

/// C: `red_newreno_test` in `picoquictest/tls_api_test.c`.
#[test]
fn red_newreno() {
    todo!("red_newreno_test")
}

/// C: `request_client_authentication_test` in `picoquictest/tls_api_test.c`.
#[test]
fn request_client_authentication() {
    todo!("request_client_authentication_test")
}

/// C: `retire_cnxid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retire_cnxid() {
    todo!("retire_cnxid_test")
}

/// C: `tls_api_retry_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry() {
    todo!("tls_api_retry_test")
}

/// C: `tls_api_retry_large_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry_large() {
    todo!("tls_api_retry_large_test")
}

/// C: `tls_retry_token_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry_token() {
    todo!("tls_retry_token_test")
}

/// C: `tls_retry_token_valid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn retry_token_valid() {
    todo!("tls_retry_token_valid_test")
}

/// C: `tls_api_client_second_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn second_loss() {
    todo!("tls_api_client_second_loss_test")
}

/// C: `server_busy_test` in `picoquictest/tls_api_test.c`.
#[test]
fn server_busy() {
    todo!("server_busy_test")
}

/// C: `tls_api_server_losses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn server_losses() {
    todo!("tls_api_server_losses_test")
}

/// C: `session_resume_test` in `picoquictest/tls_api_test.c`.
#[test]
fn session_resume() {
    todo!("session_resume_test")
}

/// C: `set_certificate_and_key_test` in `picoquictest/tls_api_test.c`.
#[test]
fn set_certificate_and_key() {
    todo!("set_certificate_and_key_test")
}

/// C: `set_verify_certificate_callback_test` in `picoquictest/tls_api_test.c`.
#[test]
fn set_verify_certificate_callback_test() {
    todo!("set_verify_certificate_callback_test")
}

/// C: `short_initial_cid_test` in `picoquictest/tls_api_test.c`.
#[test]
fn short_initial_cid() {
    todo!("short_initial_cid_test")
}

/// C: `tls_api_silence_test` in `picoquictest/tls_api_test.c`.
#[test]
fn silence_test() {
    todo!("tls_api_silence_test")
}

/// C: `spurious_retransmit_test` in `picoquictest/tls_api_test.c`.
#[test]
fn spurious_retransmit() {
    todo!("spurious_retransmit_test")
}

/// C: `test_stateless_blowback` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_blowback() {
    todo!("test_stateless_blowback")
}

/// C: `stateless_reset_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset() {
    todo!("stateless_reset_test")
}

/// C: `stateless_reset_bad_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset_bad() {
    todo!("stateless_reset_bad_test")
}

/// C: `stateless_reset_client_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset_client() {
    todo!("stateless_reset_client_test")
}

/// C: `stateless_reset_handshake_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stateless_reset_handshake() {
    todo!("stateless_reset_handshake_test")
}

/// C: `stop_sending_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stop_sending() {
    todo!("stop_sending_test")
}

/// C: `stop_sending_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stop_sending_loss() {
    todo!("stop_sending_loss_test")
}

/// C: `stream_id_max_test` in `picoquictest/tls_api_test.c`.
#[test]
fn stream_id_max() {
    todo!("stream_id_max_test")
}

/// C: `tls_api_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api() {
    todo!("tls_api_test")
}

/// C: `tls_api_alpn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_alpn() {
    todo!("tls_api_alpn_test")
}

/// C: `tls_api_connect_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_connect() {
    todo!("tls_api_connect_test")
}

/// C: `tls_api_inject_hs_ack_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_inject_hs_ack() {
    todo!("tls_api_inject_hs_ack_test")
}

/// C: `tls_api_oneway_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_oneway_stream() {
    todo!("tls_api_oneway_stream_test")
}

/// C: `tls_api_q2_and_r2_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_q2_and_r2_stream() {
    todo!("tls_api_q2_and_r2_stream_test")
}

/// C: `tls_api_q_and_r_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_q_and_r_stream() {
    todo!("tls_api_q_and_r_stream_test")
}

/// C: `tls_api_sni_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_sni() {
    todo!("tls_api_sni_test")
}

/// C: `tls_api_very_long_congestion_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_congestion() {
    todo!("tls_api_very_long_congestion_test")
}

/// C: `tls_api_very_long_max_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_max() {
    todo!("tls_api_very_long_max_test")
}

/// C: `tls_api_very_long_stream_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_stream() {
    todo!("tls_api_very_long_stream_test")
}

/// C: `tls_api_very_long_with_err_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_very_long_with_err() {
    todo!("tls_api_very_long_with_err_test")
}

/// C: `tls_api_wrong_alpn_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_api_wrong_alpn() {
    todo!("tls_api_wrong_alpn_test")
}

/// C: `tls_exporter_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_exporter() {
    todo!("tls_exporter_test")
}

/// C: `tls_zero_share_test` in `picoquictest/tls_api_test.c`.
#[test]
fn tls_zero_share() {
    todo!("tls_zero_share_test")
}

/// C: `tls_api_two_connections_test` in `picoquictest/tls_api_test.c`.
#[test]
fn two_connections() {
    todo!("tls_api_two_connections_test")
}

/// C: `unidir_test` in `picoquictest/tls_api_test.c`.
#[test]
fn unidir() {
    todo!("unidir_test")
}

/// C: `tls_api_version_invariant_test` in `picoquictest/tls_api_test.c`.
#[test]
fn version_invariant() {
    todo!("tls_api_version_invariant_test")
}

/// C: `tls_api_version_negotiation_test` in `picoquictest/tls_api_test.c`.
#[test]
fn version_negotiation() {
    todo!("tls_api_version_negotiation_test")
}

/// C: `test_version_negotiation_spoof` in `picoquictest/tls_api_test.c`.
#[test]
fn version_negotiation_spoof() {
    todo!("test_version_negotiation_spoof")
}

/// C: `virtual_time_test` in `picoquictest/tls_api_test.c`.
#[test]
fn virtual_time() {
    todo!("virtual_time_test")
}

/// C: `vn_compat_test` in `picoquictest/tls_api_test.c`.
#[test]
fn vn_compat() {
    todo!("vn_compat_test")
}

/// C: `zero_rtt_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt() {
    todo!("zero_rtt_test")
}

/// C: `zero_rtt_bad_param_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_bad_param() {
    todo!("zero_rtt_bad_param_test")
}

/// C: `zero_rtt_delay_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_delay() {
    todo!("zero_rtt_delay_test")
}

/// C: `zero_rtt_ech_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_ech() {
    todo!("zero_rtt_ech_test")
}

/// C: `zero_rtt_long_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_long() {
    todo!("zero_rtt_long_test")
}

/// C: `zero_rtt_loss_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_loss() {
    todo!("zero_rtt_loss_test")
}

/// C: `zero_rtt_many_losses_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_many_losses() {
    todo!("zero_rtt_many_losses_test")
}

/// C: `zero_rtt_no_coal_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_no_coal() {
    todo!("zero_rtt_no_coal_test")
}

/// C: `zero_rtt_retry_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_retry() {
    todo!("zero_rtt_retry_test")
}

/// C: `zero_rtt_spurious_test` in `picoquictest/tls_api_test.c`.
#[test]
fn zero_rtt_spurious() {
    todo!("zero_rtt_spurious_test")
}
