//! Test cases for `picoquictest/warptest*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `warptest_param_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_param() {
    todo!("warptest_param_test")
}

/// C: `warptest_video_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_video() {
    todo!("warptest_video_test")
}

/// C: `warptest_video_audio_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_video_audio() {
    todo!("warptest_video_audio_test")
}

/// C: `warptest_video_data_audio_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_video_data_audio() {
    todo!("warptest_video_data_audio_test")
}

/// C: `warptest_worst_test` in `picoquictest/warptest.c`.
#[test]
fn warptest_worst() {
    todo!("warptest_worst_test")
}
