//! Test cases for `picoquictest/wifitest*.c` (auto-stubbed).
//!
//! Generated by `scripts/phase3.py` from
//! `picoquic_t/picoquic_t.c`'s `test_table[]`.  Each stub
//! corresponds to one C test entry; bodies are `todo!()`
//! until the body-translation pass lands.

#![allow(non_snake_case)]

/// C: `wifi_bbr_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr() {
    todo!("wifi_bbr_test")
}

/// C: `wifi_bbr1_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr1() {
    todo!("wifi_bbr1_test")
}

/// C: `wifi_bbr1_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr1_hard() {
    todo!("wifi_bbr1_hard_test")
}

/// C: `wifi_bbr1_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr1_long() {
    todo!("wifi_bbr1_long_test")
}

/// C: `wifi_bbr_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_hard() {
    todo!("wifi_bbr_hard_test")
}

/// C: `wifi_bbr_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_long() {
    todo!("wifi_bbr_long_test")
}

/// C: `wifi_bbr_many_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_many() {
    todo!("wifi_bbr_many_test")
}

/// C: `wifi_bbr_shadow_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_bbr_shadow() {
    todo!("wifi_bbr_shadow_test")
}

/// C: `wifi_cubic_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_cubic() {
    todo!("wifi_cubic_test")
}

/// C: `wifi_cubic_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_cubic_hard() {
    todo!("wifi_cubic_hard_test")
}

/// C: `wifi_cubic_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_cubic_long() {
    todo!("wifi_cubic_long_test")
}

/// C: `wifi_reno_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_reno() {
    todo!("wifi_reno_test")
}

/// C: `wifi_reno_hard_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_reno_hard() {
    todo!("wifi_reno_hard_test")
}

/// C: `wifi_reno_long_test` in `picoquictest/wifitest.c`.
#[test]
fn wifi_reno_long() {
    todo!("wifi_reno_long_test")
}
