/* automatically generated by rust-bindgen 0.72.1 */

pub const BYTESTREAM_MAX_BUFFER_SIZE: u32 = 2560;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type sa_family_t = __uint8_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr {
    pub sa_len: __uint8_t,
    pub sa_family: sa_family_t,
    pub sa_data: [::std::os::raw::c_char; 14usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_storage {
    pub ss_len: __uint8_t,
    pub ss_family: sa_family_t,
    pub __ss_pad1: [::std::os::raw::c_char; 6usize],
    pub __ss_align: __int64_t,
    pub __ss_pad2: [::std::os::raw::c_char; 112usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquic_connection_id_t {
    pub id: [u8; 20usize],
    pub id_len: u8,
}
pub type picoquic_connection_id_t = st_picoquic_connection_id_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bytestream {
    pub data: *mut u8,
    pub size: usize,
    pub ptr: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bytestream_buf {
    pub s: bytestream,
    pub buf: [u8; 2560usize],
}
unsafe extern "C" {
    pub fn bytestream_ref_init(
        s: *mut bytestream,
        bytes: *const ::std::os::raw::c_void,
        nb_bytes: usize,
    ) -> *mut bytestream;
}
unsafe extern "C" {
    pub fn bytestream_buf_init(s: *mut bytestream_buf, nb_bytes: usize) -> *mut bytestream;
}
unsafe extern "C" {
    pub fn bytestream_alloc(s: *mut bytestream, nb_bytes: usize) -> *mut bytestream;
}
unsafe extern "C" {
    pub fn bytestream_delete(s: *mut bytestream);
}
unsafe extern "C" {
    pub fn bytestream_data(s: *mut bytestream) -> *const u8;
}
unsafe extern "C" {
    pub fn bytestream_ptr(s: *mut bytestream) -> *const u8;
}
unsafe extern "C" {
    pub fn bytestream_size(s: *mut bytestream) -> usize;
}
unsafe extern "C" {
    pub fn bytestream_length(s: *mut bytestream) -> usize;
}
unsafe extern "C" {
    pub fn bytestream_remain(s: *mut bytestream) -> usize;
}
unsafe extern "C" {
    pub fn bytestream_reset(s: *mut bytestream);
}
unsafe extern "C" {
    pub fn bytestream_clear(s: *mut bytestream);
}
unsafe extern "C" {
    pub fn bytestream_finished(s: *mut bytestream) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytestream_skip(s: *mut bytestream, nb_bytes: usize) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_int8(s: *mut bytestream, value: u8) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_int8(s: *mut bytestream, value: *mut u8) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteshow_int8(s: *mut bytestream, value: *mut u8) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_int16(s: *mut bytestream, value: u16) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_int16(s: *mut bytestream, value: *mut u16) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_int32(s: *mut bytestream, value: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_int32(s: *mut bytestream, value: *mut u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_int64(s: *mut bytestream, value: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_int64(s: *mut bytestream, value: *mut u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_vint(s: *mut bytestream, value: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_vint(s: *mut bytestream, value: *mut u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_skip_vint(s: *mut bytestream) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytestream_vint_len(value: u64) -> usize;
}
unsafe extern "C" {
    pub fn byteread_vlen(s: *mut bytestream, value: *mut usize) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_buffer(
        s: *mut bytestream,
        buffer: *const ::std::os::raw::c_void,
        length: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_buffer(
        s: *mut bytestream,
        buffer: *mut ::std::os::raw::c_void,
        length: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_cid(
        s: *mut bytestream,
        cid: *const picoquic_connection_id_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_cid(
        s: *mut bytestream,
        cid: *mut picoquic_connection_id_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteskip_cid(s: *mut bytestream) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_cstr(
        s: *mut bytestream,
        cstr: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_cstr(
        s: *mut bytestream,
        cstr: *mut ::std::os::raw::c_char,
        max_len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteskip_cstr(s: *mut bytestream) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bytewrite_addr(s: *mut bytestream, addr: *const sockaddr) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteread_addr(s: *mut bytestream, addr: *mut sockaddr_storage) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn byteskip_addr(s: *mut bytestream) -> ::std::os::raw::c_int;
}
