/* automatically generated by rust-bindgen 0.72.1 */

pub const PRIst: &[u8; 3] = b"zu\0";
pub const PICOQUIC_SENDER: u32 = 1;
pub const PICOQUIC_PACKET: u32 = 2;
pub const PICOQUIC_QUICCTX: u32 = 3;
pub const PICOQUIC_FRAME: u32 = 4;
pub const PICOQUIC_LOSS_RECOVERY: u32 = 5;
pub const PICOQUIC_DEFAULT_SOLUTION_DIR: &[u8; 3] = b"./\0";
pub const PICOQUIC_FILE_SEPARATOR: &[u8; 2] = b"/\0";
pub const DBG_PRINTF_FILENAME_MAX: u32 = 24;
pub const PICOQUIC_TEST_SNI: &[u8; 17] = b"test.example.com\0";
pub const PICOQUIC_TEST_FILE_SERVER_CERT: &[u8; 15] = b"certs/cert.pem\0";
pub const PICOQUIC_TEST_FILE_SERVER_BAD_CERT: &[u8; 18] = b"certs/badcert.pem\0";
pub const PICOQUIC_TEST_FILE_SERVER_KEY: &[u8; 14] = b"certs/key.pem\0";
pub const PICOQUIC_TEST_FILE_CERT_STORE: &[u8; 18] = b"certs/test-ca.crt\0";
pub const PICOQUIC_TEST_FILE_SERVER_CERT_ECDSA: &[u8; 21] = b"certs/ecdsa/cert.pem\0";
pub const PICOQUIC_TEST_FILE_SERVER_KEY_ECDSA: &[u8; 20] = b"certs/ecdsa/key.pem\0";
pub const PICOQUIC_TEST_ECH_PUB_KEY: &[u8; 21] = b"certs/ech/public.pem\0";
pub const PICOQUIC_TEST_ECH_PRIVATE_KEY: &[u8; 22] = b"certs/ech/private.pem\0";
pub const PICOQUIC_TEST_ECH_CONFIG: &[u8; 25] = b"certs/ech/ech_config.txt\0";
pub const PICOQUIC_TEST_ECH_CERT: &[u8; 23] = b"certs/ech/ech_cert.pem\0";
pub const PICOQUIC_TEST_ECH_RR_REF: &[u8; 21] = b"certs/ech/ech_rr.txt\0";
pub const PICOQUIC_TEST_ECH_CONFIG_REF: &[u8; 25] = b"certs/ech/ech_config.txt\0";
pub const PICOQUIC_TEST_FILE_SERVER_CERT_RSA: &[u8; 19] = b"certs/rsa/cert.pem\0";
pub const PICOQUIC_TEST_FILE_SERVER_KEY_RSA: &[u8; 18] = b"certs/rsa/key.pem\0";
pub const PICOQUIC_TEST_FILE_SERVER_CERT_ED25519: &[u8; 30] = b"certs/mtls_ed25519/server.crt\0";
pub const PICOQUIC_TEST_FILE_SERVER_KEY_ED25519: &[u8; 30] = b"certs/mtls_ed25519/server.key\0";
pub const PICOQUIC_TEST_FILE_CLIENT_CERT_ED25519: &[u8; 30] = b"certs/mtls_ed25519/client.crt\0";
pub const PICOQUIC_TEST_FILE_CLIENT_KEY_ED25519: &[u8; 30] = b"certs/mtls_ed25519/client.key\0";
pub const PICOQUIC_TEST_FILE_CERT_STORE_ED25519: &[u8; 26] = b"certs/mtls_ed25519/ca.crt\0";
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __darwin_off_t = __int64_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type pthread_cond_t = __darwin_pthread_cond_t;
pub type pthread_mutex_t = __darwin_pthread_mutex_t;
pub type pthread_t = __darwin_pthread_t;
pub type sa_family_t = __uint8_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr {
    pub sa_len: __uint8_t,
    pub sa_family: sa_family_t,
    pub sa_data: [::std::os::raw::c_char; 14usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_storage {
    pub ss_len: __uint8_t,
    pub ss_family: sa_family_t,
    pub __ss_pad1: [::std::os::raw::c_char; 6usize],
    pub __ss_align: __int64_t,
    pub __ss_pad2: [::std::os::raw::c_char; 112usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquic_connection_id_t {
    pub id: [u8; 20usize],
    pub id_len: u8,
}
pub type picoquic_connection_id_t = st_picoquic_connection_id_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquic_tp_preferred_address_t {
    pub is_defined: ::std::os::raw::c_int,
    pub ipv4Address: [u8; 4usize],
    pub ipv4Port: u16,
    pub ipv6Address: [u8; 16usize],
    pub ipv6Port: u16,
    pub connection_id: picoquic_connection_id_t,
    pub statelessResetToken: [u8; 16usize],
}
pub type picoquic_tp_preferred_address_t = st_picoquic_tp_preferred_address_t;
pub type fpos_t = __darwin_off_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sbuf {
    pub _base: *mut ::std::os::raw::c_uchar,
    pub _size: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sFILEX {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sFILE {
    pub _p: *mut ::std::os::raw::c_uchar,
    pub _r: ::std::os::raw::c_int,
    pub _w: ::std::os::raw::c_int,
    pub _flags: ::std::os::raw::c_short,
    pub _file: ::std::os::raw::c_short,
    pub _bf: __sbuf,
    pub _lbfsize: ::std::os::raw::c_int,
    pub _cookie: *mut ::std::os::raw::c_void,
    pub _close: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
    >,
    pub _read: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *mut ::std::os::raw::c_char,
            __n: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub _seek: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: fpos_t,
            arg3: ::std::os::raw::c_int,
        ) -> fpos_t,
    >,
    pub _write: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_char,
            __n: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub _ub: __sbuf,
    pub _extra: *mut __sFILEX,
    pub _ur: ::std::os::raw::c_int,
    pub _ubuf: [::std::os::raw::c_uchar; 3usize],
    pub _nbuf: [::std::os::raw::c_uchar; 1usize],
    pub _lb: __sbuf,
    pub _blksize: ::std::os::raw::c_int,
    pub _offset: fpos_t,
}
pub type FILE = __sFILE;
unsafe extern "C" {
    pub fn debug_set_stream(F: *mut FILE);
}
unsafe extern "C" {
    pub fn debug_printf(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn debug_printf_push_stream(f: *mut FILE);
}
unsafe extern "C" {
    pub fn debug_printf_pop_stream();
}
unsafe extern "C" {
    pub fn debug_printf_suspend();
}
unsafe extern "C" {
    pub fn debug_printf_resume();
}
unsafe extern "C" {
    pub fn debug_printf_reset(suspended: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_string_create(
        original: *const ::std::os::raw::c_char,
        len: usize,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn picoquic_string_duplicate(
        original: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn picoquic_string_free(str_: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn picoquic_sprintf(
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        nb_chars: *mut usize,
        fmt: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static picoquic_null_connection_id: picoquic_connection_id_t;
}
unsafe extern "C" {
    pub fn picoquic_format_connection_id(
        bytes: *mut u8,
        bytes_max: usize,
        cnx_id: picoquic_connection_id_t,
    ) -> u8;
}
unsafe extern "C" {
    pub fn picoquic_parse_connection_id(
        bytes: *const u8,
        len: u8,
        cnx_id: *mut picoquic_connection_id_t,
    ) -> u8;
}
unsafe extern "C" {
    pub fn picoquic_is_connection_id_null(
        cnx_id: *const picoquic_connection_id_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_compare_connection_id(
        cnx_id1: *const picoquic_connection_id_t,
        cnx_id2: *const picoquic_connection_id_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_connection_id_hash(
        cid: *const picoquic_connection_id_t,
        hash_seed: *const u8,
    ) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_val64_connection_id(cnx_id: picoquic_connection_id_t) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_hash_addr_bytes(addr: *const sockaddr, bytes: *mut u8) -> usize;
}
unsafe extern "C" {
    pub fn picoquic_hash_addr(addr: *const sockaddr, hash_seed: *const u8) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_parse_hexa(
        hex_input: *const ::std::os::raw::c_char,
        input_length: usize,
        bin_output: *mut u8,
        output_max: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn picoquic_parse_connection_id_hexa(
        hex_input: *const ::std::os::raw::c_char,
        input_length: usize,
        cnx_id: *mut picoquic_connection_id_t,
    ) -> u8;
}
unsafe extern "C" {
    pub fn picoquic_print_connection_id_hexa(
        buf: *mut ::std::os::raw::c_char,
        buf_len: usize,
        cnxid: *const picoquic_connection_id_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_compare_addr(
        expected: *const sockaddr,
        actual: *const sockaddr,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_compare_ip_addr(
        expected: *const sockaddr,
        actual: *const sockaddr,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_get_addr_port(addr: *const sockaddr) -> u16;
}
unsafe extern "C" {
    pub fn picoquic_set_addr_port(addr: *const sockaddr, port: u16);
}
unsafe extern "C" {
    pub fn picoquic_addr_length(addr: *const sockaddr) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_store_addr(stored_addr: *mut sockaddr_storage, addr: *const sockaddr);
}
unsafe extern "C" {
    pub fn picoquic_get_ip_addr(addr: *mut sockaddr, ip_addr: *mut *mut u8, ip_addr_len: *mut u8);
}
unsafe extern "C" {
    pub fn picoquic_store_text_addr(
        stored_addr: *mut sockaddr_storage,
        ip_address_text: *const ::std::os::raw::c_char,
        port: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_addr_text(
        addr: *const sockaddr,
        text: *mut ::std::os::raw::c_char,
        text_size: usize,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn picoquic_store_loopback_addr(
        stored_addr: *mut sockaddr_storage,
        addr_family: ::std::os::raw::c_int,
        port: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_set_preferred_address(
        preferred: *mut picoquic_tp_preferred_address_t,
        v4_text: *const ::std::os::raw::c_char,
        v6_text: *const ::std::os::raw::c_char,
        preferred_port: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_set_solution_dir(solution_dir: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn picoquic_get_input_path(
        target_file_path: *mut ::std::os::raw::c_char,
        file_path_max: usize,
        solution_path: *const ::std::os::raw::c_char,
        file_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_file_open_ex(
        file_name: *const ::std::os::raw::c_char,
        flags: *const ::std::os::raw::c_char,
        last_err: *mut ::std::os::raw::c_int,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn picoquic_file_open(
        file_name: *const ::std::os::raw::c_char,
        flags: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn picoquic_file_close(F: *mut FILE) -> *mut FILE;
}
unsafe extern "C" {
    pub fn picoquic_file_delete(
        file_name: *const ::std::os::raw::c_char,
        last_err: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_frames_fixed_skip(
        bytes: *const u8,
        bytes_max: *const u8,
        size: u64,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_varint_skip(bytes: *const u8, bytes_max: *const u8) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_varint_decode(
        bytes: *const u8,
        bytes_max: *const u8,
        n64: *mut u64,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_varlen_decode(
        bytes: *const u8,
        bytes_max: *const u8,
        n: *mut usize,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint8_decode(
        bytes: *const u8,
        bytes_max: *const u8,
        n: *mut u8,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint16_decode(
        bytes: *const u8,
        bytes_max: *const u8,
        n: *mut u16,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint32_decode(
        bytes: *const u8,
        bytes_max: *const u8,
        n: *mut u32,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint64_decode(
        bytes: *const u8,
        bytes_max: *const u8,
        n: *mut u64,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_length_data_skip(bytes: *const u8, bytes_max: *const u8) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_cid_decode(
        bytes: *const u8,
        bytes_max: *const u8,
        cid: *mut picoquic_connection_id_t,
    ) -> *const u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_varint_encode_length(n64: u64) -> usize;
}
unsafe extern "C" {
    pub fn picoquic_frames_varint_encode(bytes: *mut u8, bytes_max: *const u8, n64: u64)
        -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_varlen_encode(bytes: *mut u8, bytes_max: *const u8, n: usize)
        -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint8_encode(bytes: *mut u8, bytes_max: *const u8, n: u8) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint16_encode(bytes: *mut u8, bytes_max: *const u8, n: u16) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint24_encode(bytes: *mut u8, bytes_max: *const u8, n: u32) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint32_encode(bytes: *mut u8, bytes_max: *const u8, n: u32) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_uint64_encode(bytes: *mut u8, bytes_max: *const u8, n: u64) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_length_data_encode(
        bytes: *mut u8,
        bytes_max: *const u8,
        l: usize,
        v: *const u8,
    ) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_cid_encode(
        bytes: *mut u8,
        bytes_max: *const u8,
        cid: *const picoquic_connection_id_t,
    ) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_frames_charz_encode(
        bytes: *mut u8,
        bytes_max: *const u8,
        s: *const ::std::os::raw::c_char,
    ) -> *mut u8;
}
unsafe extern "C" {
    pub fn picoquic_constant_time_memcmp(
        x: *const u8,
        y: *const u8,
        l: usize,
    ) -> ::std::os::raw::c_int;
}
pub type picoquic_thread_fn = ::std::option::Option<
    unsafe extern "C" fn(lpParam: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquic_event_t {
    pub mutex: pthread_mutex_t,
    pub cond: pthread_cond_t,
}
pub type picoquic_event_t = st_picoquic_event_t;
unsafe extern "C" {
    pub fn picoquic_create_thread(
        thread: *mut pthread_t,
        thread_fn: picoquic_thread_fn,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_wait_thread(thread: pthread_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_delete_thread(thread: *mut pthread_t);
}
unsafe extern "C" {
    pub fn picoquic_create_mutex(mutex: *mut pthread_mutex_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_delete_mutex(mutex: *mut pthread_mutex_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_lock_mutex(mutex: *mut pthread_mutex_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_unlock_mutex(mutex: *mut pthread_mutex_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_create_event(event: *mut picoquic_event_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_delete_event(event: *mut picoquic_event_t);
}
unsafe extern "C" {
    pub fn picoquic_signal_event(event: *mut picoquic_event_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_wait_for_event(
        event: *mut picoquic_event_t,
        microsec_wait: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picoquic_uniform_random(rnd_max: u64) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_test_random(random_context: *mut u64) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_test_random_bytes(random_context: *mut u64, bytes: *mut u8, bytes_max: usize);
}
unsafe extern "C" {
    pub fn picoquic_test_uniform_random(random_context: *mut u64, rnd_max: u64) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_test_gauss_random(random_context: *mut u64) -> f64;
}
unsafe extern "C" {
    pub fn picoquic_test_poisson_random(
        random_context: *mut u64,
        exp_minus_lambda_2_30: u64,
    ) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_uint8_to_str(
        text: *mut ::std::os::raw::c_char,
        text_len: usize,
        data: *const u8,
        data_len: usize,
    ) -> *mut ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquictest_sim_packet_t {
    pub next_packet: *mut st_picoquictest_sim_packet_t,
    pub arrival_time: u64,
    pub length: usize,
    pub addr_from: sockaddr_storage,
    pub addr_to: sockaddr_storage,
    pub ecn_mark: u8,
    pub bytes: [u8; 1536usize],
}
pub type picoquictest_sim_packet_t = st_picoquictest_sim_packet_t;
pub type picoquictest_sim_link_t = st_picoquictest_sim_link_t;
pub type picoquictest_aqm_t = st_picoquictest_aqm_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquictest_aqm_t {
    pub submit: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut picoquictest_aqm_t,
            link: *mut picoquictest_sim_link_t,
            packet: *mut picoquictest_sim_packet_t,
            current_time: u64,
        ),
    >,
    pub reset: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut picoquictest_aqm_t,
            link: *mut st_picoquictest_sim_link_t,
            current_time: u64,
        ),
    >,
    pub release: ::std::option::Option<
        unsafe extern "C" fn(self_: *mut picoquictest_aqm_t, link: *mut st_picoquictest_sim_link_t),
    >,
    pub has_pending: ::std::option::Option<
        unsafe extern "C" fn(self_: *mut picoquictest_aqm_t) -> ::std::os::raw::c_int,
    >,
    pub admit_pending: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut picoquictest_aqm_t,
            link: *mut st_picoquictest_sim_link_t,
            current_time: u64,
        ),
    >,
}
pub const picoquic_jitter_mode_jitter_gauss: picoquic_jitter_mode = 0;
pub const picoquic_jitter_mode_jitter_wifi: picoquic_jitter_mode = 1;
pub type picoquic_jitter_mode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquictest_sim_link_t {
    pub next_send_time: u64,
    pub queue_time: u64,
    pub resume_time: u64,
    pub queue_delay_max: u64,
    pub picosec_per_byte: u64,
    pub microsec_latency: u64,
    pub packets_dropped: u64,
    pub packets_sent: u64,
    pub jitter: u64,
    pub jitter_mode: picoquic_jitter_mode,
    pub jitter_seed: u64,
    pub path_mtu: usize,
    pub first_packet: *mut picoquictest_sim_packet_t,
    pub last_packet: *mut picoquictest_sim_packet_t,
    pub loss_mask: *mut u64,
    pub nb_loss_in_burst: u64,
    pub packets_between_losses: u64,
    pub packets_sent_next_burst: u64,
    pub nb_losses_this_burst: u64,
    pub end_of_burst_time: u64,
    pub aqm_state: *mut st_picoquictest_aqm_t,
    pub is_switched_off: ::std::os::raw::c_int,
    pub is_unreachable: ::std::os::raw::c_int,
    pub is_suspended: ::std::os::raw::c_int,
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_create(
        data_rate_in_gps: f64,
        microsec_latency: u64,
        loss_mask: *mut u64,
        queue_delay_max: u64,
        current_time: u64,
    ) -> *mut picoquictest_sim_link_t;
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_delete(link: *mut picoquictest_sim_link_t);
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_create_packet() -> *mut picoquictest_sim_packet_t;
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_next_arrival(
        link: *mut picoquictest_sim_link_t,
        current_time: u64,
    ) -> u64;
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_admit_pending(
        link: *mut picoquictest_sim_link_t,
        current_time: u64,
    );
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_next_admission(
        link: *mut picoquictest_sim_link_t,
        current_time: u64,
        next_time: u64,
    ) -> u64;
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_dequeue(
        link: *mut picoquictest_sim_link_t,
        current_time: u64,
    ) -> *mut picoquictest_sim_packet_t;
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_submit(
        link: *mut picoquictest_sim_link_t,
        packet: *mut picoquictest_sim_packet_t,
        current_time: u64,
    );
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_enqueue(
        link: *mut picoquictest_sim_link_t,
        packet: *mut picoquictest_sim_packet_t,
        current_time: u64,
        should_drop: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_transmit_time(
        link: *mut picoquictest_sim_link_t,
        packet: *mut picoquictest_sim_packet_t,
    ) -> u64;
}
unsafe extern "C" {
    pub fn picoquictest_sim_link_queue_delay(
        link: *mut picoquictest_sim_link_t,
        current_time: u64,
    ) -> u64;
}
unsafe extern "C" {
    pub fn picoquic_test_simlink_suspend(
        link: *mut picoquictest_sim_link_t,
        time_end_of_interval: u64,
        simulate_receive: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub static mut picoquic_solution_dir: *const ::std::os::raw::c_char;
}
