// bindgen failed (exit 1).
// command: bindgen /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h --allowlist-file '.*picoquic/picoquic_crypto_provider_api\.h$' --no-layout-tests -o /Users/richbarn/Projects/picoquic/xlate/bindgen_baseline/picoquic/picoquic_crypto_provider_api.rs -- -include /Users/richbarn/Projects/picoquic/picoquic/picoquic.h -include /Users/richbarn/Projects/picoquic/picoquic/picoquic_internal.h -DPTLS_WITHOUT_FUSION -I/Users/richbarn/Projects/picoquic/build/_deps/picotls-src/include -I/opt/homebrew/Cellar/openssl@3/3.6.2/include -I/Users/richbarn/Projects/picoquic/picoquic -I/Users/richbarn/Projects/picoquic/c4/src -I/Users/richbarn/Projects/picoquic/picoquic_mbedtls -std=gnu11 -O3 -Wall -fno-exceptions -fno-signed-zeros -fno-trapping-math -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
// stderr:
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:35:40: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:36:51: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:37:46: error: unknown type name 'ptls_hpke_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:38:37: error: unknown type name 'ptls_hpke_kem_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:40:52: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:42:77: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:44:57: error: unknown type name 'ptls_sign_certificate_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:49:57: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:52:59: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:54:51: error: unknown type name 'ptls_key_exchange_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:55:46: error: unknown type name 'ptls_key_exchange_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:79:9: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:80:9: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:86:12: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:87:12: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:89:12: error: unknown type name 'ptls_hpke_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:91:12: error: unknown type name 'ptls_hpke_kem_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:114:9: error: unknown type name 'ptls_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:117:9: error: unknown type name 'ptls_raw_extension_t'
//   fatal error: too many errors emitted, stopping now [-ferror-limit=]
//   Unable to generate bindings: clang diagnosed error: /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:35:40: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:36:51: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:37:46: error: unknown type name 'ptls_hpke_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:38:37: error: unknown type name 'ptls_hpke_kem_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:40:52: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:42:77: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:44:57: error: unknown type name 'ptls_sign_certificate_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:49:57: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:52:59: error: unknown type name 'ptls_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:54:51: error: unknown type name 'ptls_key_exchange_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:55:46: error: unknown type name 'ptls_key_exchange_context_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:79:9: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:80:9: error: unknown type name 'ptls_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:86:12: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:87:12: error: unknown type name 'ptls_key_exchange_algorithm_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:89:12: error: unknown type name 'ptls_hpke_cipher_suite_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:91:12: error: unknown type name 'ptls_hpke_kem_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:114:9: error: unknown type name 'ptls_t'
//   /Users/richbarn/Projects/picoquic/picoquic/picoquic_crypto_provider_api.h:117:9: error: unknown type name 'ptls_raw_extension_t'
//   fatal error: too many errors emitted, stopping now [-ferror-limit=]
//   
