/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _picohash_item {
    pub hash: u64,
    pub next_in_bin: *mut _picohash_item,
    pub key: *const ::std::os::raw::c_void,
}
pub type picohash_item = _picohash_item;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct picohash_table {
    pub hash_bin: *mut *mut picohash_item,
    pub nb_bin: usize,
    pub count: usize,
    pub hash_seed: *const u8,
    pub picohash_hash: ::std::option::Option<
        unsafe extern "C" fn(arg1: *const ::std::os::raw::c_void, arg2: *const u8) -> u64,
    >,
    pub picohash_compare: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *const ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub picohash_key_to_item: ::std::option::Option<
        unsafe extern "C" fn(arg1: *const ::std::os::raw::c_void) -> *mut picohash_item,
    >,
}
unsafe extern "C" {
    pub fn picohash_create(
        nb_bin: usize,
        picohash_hash: ::std::option::Option<
            unsafe extern "C" fn(arg1: *const ::std::os::raw::c_void, arg2: *const u8) -> u64,
        >,
        picohash_compute: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const ::std::os::raw::c_void,
                arg2: *const ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
    ) -> *mut picohash_table;
}
unsafe extern "C" {
    pub fn picohash_create_ex(
        nb_bin: usize,
        picohash_hash: ::std::option::Option<
            unsafe extern "C" fn(arg1: *const ::std::os::raw::c_void, arg2: *const u8) -> u64,
        >,
        picohash_compare: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const ::std::os::raw::c_void,
                arg2: *const ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        picohash_key_to_item: ::std::option::Option<
            unsafe extern "C" fn(arg1: *const ::std::os::raw::c_void) -> *mut picohash_item,
        >,
        hash_seed: *const u8,
    ) -> *mut picohash_table;
}
unsafe extern "C" {
    pub fn picohash_retrieve(
        hash_table: *mut picohash_table,
        key: *const ::std::os::raw::c_void,
    ) -> *mut picohash_item;
}
unsafe extern "C" {
    pub fn picohash_insert(
        hash_table: *mut picohash_table,
        key: *const ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn picohash_delete_item(
        hash_table: *mut picohash_table,
        item: *mut picohash_item,
        delete_key_too: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn picohash_delete_key(
        hash_table: *mut picohash_table,
        key: *mut ::std::os::raw::c_void,
        delete_key_too: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn picohash_delete(hash_table: *mut picohash_table, delete_key_too: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn picohash_bytes(key: *const u8, length: usize, hash_seed: *const u8) -> u64;
}
unsafe extern "C" {
    pub fn picohash_siphash(bytes: *const u8, length: usize, hash_seed: *const u8) -> u64;
}
