/* automatically generated by rust-bindgen 0.72.1 */

pub const DUALQ_MAX_LINK_RATE: u32 = 125000000;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type sa_family_t = __uint8_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_storage {
    pub ss_len: __uint8_t,
    pub ss_family: sa_family_t,
    pub __ss_pad1: [::std::os::raw::c_char; 6usize],
    pub __ss_align: __int64_t,
    pub __ss_pad2: [::std::os::raw::c_char; 112usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquictest_sim_packet_t {
    pub next_packet: *mut st_picoquictest_sim_packet_t,
    pub arrival_time: u64,
    pub length: usize,
    pub addr_from: sockaddr_storage,
    pub addr_to: sockaddr_storage,
    pub ecn_mark: u8,
    pub bytes: [u8; 1536usize],
}
pub type picoquictest_sim_packet_t = st_picoquictest_sim_packet_t;
pub type picoquictest_sim_link_t = st_picoquictest_sim_link_t;
pub type picoquictest_aqm_t = st_picoquictest_aqm_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquictest_aqm_t {
    pub submit: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut picoquictest_aqm_t,
            link: *mut picoquictest_sim_link_t,
            packet: *mut picoquictest_sim_packet_t,
            current_time: u64,
        ),
    >,
    pub reset: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut picoquictest_aqm_t,
            link: *mut st_picoquictest_sim_link_t,
            current_time: u64,
        ),
    >,
    pub release: ::std::option::Option<
        unsafe extern "C" fn(self_: *mut picoquictest_aqm_t, link: *mut st_picoquictest_sim_link_t),
    >,
    pub has_pending: ::std::option::Option<
        unsafe extern "C" fn(self_: *mut picoquictest_aqm_t) -> ::std::os::raw::c_int,
    >,
    pub admit_pending: ::std::option::Option<
        unsafe extern "C" fn(
            self_: *mut picoquictest_aqm_t,
            link: *mut st_picoquictest_sim_link_t,
            current_time: u64,
        ),
    >,
}
pub const picoquic_jitter_mode_jitter_gauss: picoquic_jitter_mode = 0;
pub const picoquic_jitter_mode_jitter_wifi: picoquic_jitter_mode = 1;
pub type picoquic_jitter_mode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picoquictest_sim_link_t {
    pub next_send_time: u64,
    pub queue_time: u64,
    pub resume_time: u64,
    pub queue_delay_max: u64,
    pub picosec_per_byte: u64,
    pub microsec_latency: u64,
    pub packets_dropped: u64,
    pub packets_sent: u64,
    pub jitter: u64,
    pub jitter_mode: picoquic_jitter_mode,
    pub jitter_seed: u64,
    pub path_mtu: usize,
    pub first_packet: *mut picoquictest_sim_packet_t,
    pub last_packet: *mut picoquictest_sim_packet_t,
    pub loss_mask: *mut u64,
    pub nb_loss_in_burst: u64,
    pub packets_between_losses: u64,
    pub packets_sent_next_burst: u64,
    pub nb_losses_this_burst: u64,
    pub end_of_burst_time: u64,
    pub aqm_state: *mut st_picoquictest_aqm_t,
    pub is_switched_off: ::std::os::raw::c_int,
    pub is_unreachable: ::std::os::raw::c_int,
    pub is_suspended: ::std::os::raw::c_int,
}
unsafe extern "C" {
    pub fn dualq_configure(
        link: *mut picoquictest_sim_link_t,
        l4s_max: u64,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_dualq_queue_t {
    pub queue_bytes: u64,
    pub count: ::std::os::raw::c_int,
    pub sum_p: f64,
    pub queue_first: *mut picoquictest_sim_packet_t,
    pub queue_last: *mut picoquictest_sim_packet_t,
}
pub type dualq_queue_t = st_dualq_queue_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_dualq_state_t {
    pub super_: st_picoquictest_aqm_t,
    pub target: u64,
    pub k: f64,
    pub p_Cmax: f64,
    pub Tupdate: u64,
    pub pi2_alpha: f64,
    pub pi2_beta: f64,
    pub maxTh: u64,
    pub minTh: u64,
    pub range: u64,
    pub p_Lmax: f64,
    pub limit: u64,
    pub schedule_tick: ::std::os::raw::c_int,
    pub lq: dualq_queue_t,
    pub cq: dualq_queue_t,
    pub curq: i64,
    pub prevq: i64,
    pub update_next: u64,
    pub lq_average_queue: u64,
    pub pprime: f64,
    pub pprime_L: f64,
    pub p_L: f64,
    pub p_CL: f64,
    pub p_C: f64,
    pub last_input_time: u64,
}
pub type dualq_state_t = st_dualq_state_t;
unsafe extern "C" {
    pub fn dualq_enqueue_queue(xq: *mut dualq_queue_t, packet: *mut picoquictest_sim_packet_t);
}
unsafe extern "C" {
    pub fn dualq_dequeue_one(
        dualq: *mut dualq_state_t,
        current_time: u64,
        should_drop: *mut ::std::os::raw::c_int,
    ) -> *mut picoquictest_sim_packet_t;
}
