/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picosplay_node_t {
    pub parent: *mut st_picosplay_node_t,
    pub left: *mut st_picosplay_node_t,
    pub right: *mut st_picosplay_node_t,
}
pub type picosplay_node_t = st_picosplay_node_t;
pub type picosplay_comparator = ::std::option::Option<
    unsafe extern "C" fn(
        left: *mut ::std::os::raw::c_void,
        right: *mut ::std::os::raw::c_void,
    ) -> i64,
>;
pub type picosplay_create = ::std::option::Option<
    unsafe extern "C" fn(value: *mut ::std::os::raw::c_void) -> *mut picosplay_node_t,
>;
pub type picosplay_delete_node = ::std::option::Option<
    unsafe extern "C" fn(tree: *mut ::std::os::raw::c_void, node: *mut picosplay_node_t),
>;
pub type picosplay_node_value = ::std::option::Option<
    unsafe extern "C" fn(node: *mut picosplay_node_t) -> *mut ::std::os::raw::c_void,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_picosplay_tree_t {
    pub root: *mut picosplay_node_t,
    pub comp: picosplay_comparator,
    pub create: picosplay_create,
    pub delete_node: picosplay_delete_node,
    pub node_value: picosplay_node_value,
    pub size: ::std::os::raw::c_int,
}
pub type picosplay_tree_t = st_picosplay_tree_t;
unsafe extern "C" {
    pub fn picosplay_init_tree(
        tree: *mut picosplay_tree_t,
        comp: picosplay_comparator,
        create: picosplay_create,
        delete_node: picosplay_delete_node,
        node_value: picosplay_node_value,
    );
}
unsafe extern "C" {
    pub fn picosplay_new_tree(
        comp: picosplay_comparator,
        create: picosplay_create,
        delete_node: picosplay_delete_node,
        node_value: picosplay_node_value,
    ) -> *mut picosplay_tree_t;
}
unsafe extern "C" {
    pub fn picosplay_insert(
        tree: *mut picosplay_tree_t,
        value: *mut ::std::os::raw::c_void,
    ) -> *mut picosplay_node_t;
}
unsafe extern "C" {
    pub fn picosplay_find(
        tree: *mut picosplay_tree_t,
        value: *mut ::std::os::raw::c_void,
    ) -> *mut picosplay_node_t;
}
unsafe extern "C" {
    pub fn picosplay_find_previous(
        tree: *mut picosplay_tree_t,
        value: *mut ::std::os::raw::c_void,
    ) -> *mut picosplay_node_t;
}
unsafe extern "C" {
    pub fn picosplay_first(tree: *mut picosplay_tree_t) -> *mut picosplay_node_t;
}
unsafe extern "C" {
    pub fn picosplay_previous(node: *mut picosplay_node_t) -> *mut picosplay_node_t;
}
unsafe extern "C" {
    pub fn picosplay_next(node: *mut picosplay_node_t) -> *mut picosplay_node_t;
}
unsafe extern "C" {
    pub fn picosplay_last(tree: *mut picosplay_tree_t) -> *mut picosplay_node_t;
}
unsafe extern "C" {
    pub fn picosplay_delete(tree: *mut picosplay_tree_t, value: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn picosplay_delete_hint(tree: *mut picosplay_tree_t, node: *mut picosplay_node_t);
}
unsafe extern "C" {
    pub fn picosplay_empty_tree(tree: *mut picosplay_tree_t);
}
