/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn siphash(
        in_: *const ::std::os::raw::c_void,
        inlen: usize,
        k: *const ::std::os::raw::c_void,
        out: *mut u8,
        outlen: usize,
    ) -> ::std::os::raw::c_int;
}
